#pragma once

#include "igen_immintrin_fallback.h"

#define _igen_mm_cvtsi32_ss             _igen_fb_mm_cvtsi32_ss
#define _igen_mm_cvtsi64_ss             _igen_fb_mm_cvtsi64_ss
#define _igen_mm_cvtpi32_ps             _igen_fb_mm_cvtpi32_ps
#define _igen_mm_cvtpi16_ps             _igen_fb_mm_cvtpi16_ps
#define _igen_mm_cvtpu16_ps             _igen_fb_mm_cvtpu16_ps
#define _igen_mm_cvtpi8_ps              _igen_fb_mm_cvtpi8_ps
#define _igen_mm_cvtpu8_ps              _igen_fb_mm_cvtpu8_ps
#define _igen_mm_cvtpi32x2_ps           _igen_fb_mm_cvtpi32x2_ps
#define _igen_mm_add_ss                 _igen_fb_mm_add_ss
#define _igen_mm_add_ps                 _igen_fb_mm_add_ps
#define _igen_mm_sub_ss                 _igen_fb_mm_sub_ss
#define _igen_mm_sub_ps                 _igen_fb_mm_sub_ps
#define _igen_mm_mul_ss                 _igen_fb_mm_mul_ss
#define _igen_mm_mul_ps                 _igen_fb_mm_mul_ps
#define _igen_mm_div_ss                 _igen_fb_mm_div_ss
#define _igen_mm_div_ps                 _igen_fb_mm_div_ps
#define _igen_mm_sqrt_ss                _igen_fb_mm_sqrt_ss
#define _igen_mm_sqrt_ps                _igen_fb_mm_sqrt_ps
#define _igen_mm_rcp_ss                 _igen_fb_mm_rcp_ss
#define _igen_mm_rcp_ps                 _igen_fb_mm_rcp_ps
#define _igen_mm_rsqrt_ss               _igen_fb_mm_rsqrt_ss
#define _igen_mm_rsqrt_ps               _igen_fb_mm_rsqrt_ps
#define _igen_mm_min_ss                 _igen_fb_mm_min_ss
#define _igen_mm_min_ps                 _igen_fb_mm_min_ps
#define _igen_mm_max_ss                 _igen_fb_mm_max_ss
#define _igen_mm_max_ps                 _igen_fb_mm_max_ps
#define _igen_mm_and_ps                 _igen_fb_mm_and_ps
#define _igen_mm_andnot_ps              _igen_fb_mm_andnot_ps
#define _igen_mm_or_ps                  _igen_fb_mm_or_ps
#define _igen_mm_xor_ps                 _igen_fb_mm_xor_ps
#define _igen_mm_cmpeq_ss               _igen_fb_mm_cmpeq_ss
#define _igen_mm_cmpeq_ps               _igen_fb_mm_cmpeq_ps
#define _igen_mm_cmplt_ss               _igen_fb_mm_cmplt_ss
#define _igen_mm_cmplt_ps               _igen_fb_mm_cmplt_ps
#define _igen_mm_cmple_ss               _igen_fb_mm_cmple_ss
#define _igen_mm_cmple_ps               _igen_fb_mm_cmple_ps
#define _igen_mm_cmpgt_ss               _igen_fb_mm_cmpgt_ss
#define _igen_mm_cmpgt_ps               _igen_fb_mm_cmpgt_ps
#define _igen_mm_cmpge_ss               _igen_fb_mm_cmpge_ss
#define _igen_mm_cmpge_ps               _igen_fb_mm_cmpge_ps
#define _igen_mm_cmpneq_ss              _igen_fb_mm_cmpneq_ss
#define _igen_mm_cmpneq_ps              _igen_fb_mm_cmpneq_ps
#define _igen_mm_cmpnlt_ss              _igen_fb_mm_cmpnlt_ss
#define _igen_mm_cmpnlt_ps              _igen_fb_mm_cmpnlt_ps
#define _igen_mm_cmpnle_ss              _igen_fb_mm_cmpnle_ss
#define _igen_mm_cmpnle_ps              _igen_fb_mm_cmpnle_ps
#define _igen_mm_cmpngt_ss              _igen_fb_mm_cmpngt_ss
#define _igen_mm_cmpngt_ps              _igen_fb_mm_cmpngt_ps
#define _igen_mm_cmpnge_ss              _igen_fb_mm_cmpnge_ss
#define _igen_mm_cmpnge_ps              _igen_fb_mm_cmpnge_ps
#define _igen_mm_cmpord_ss              _igen_fb_mm_cmpord_ss
#define _igen_mm_cmpord_ps              _igen_fb_mm_cmpord_ps
#define _igen_mm_cmpunord_ss            _igen_fb_mm_cmpunord_ss
#define _igen_mm_cmpunord_ps            _igen_fb_mm_cmpunord_ps
#define _igen_mm_comieq_ss              _igen_fb_mm_comieq_ss
#define _igen_mm_comilt_ss              _igen_fb_mm_comilt_ss
#define _igen_mm_comile_ss              _igen_fb_mm_comile_ss
#define _igen_mm_comigt_ss              _igen_fb_mm_comigt_ss
#define _igen_mm_comige_ss              _igen_fb_mm_comige_ss
#define _igen_mm_comineq_ss             _igen_fb_mm_comineq_ss
#define _igen_mm_ucomieq_ss             _igen_fb_mm_ucomieq_ss
#define _igen_mm_ucomilt_ss             _igen_fb_mm_ucomilt_ss
#define _igen_mm_ucomile_ss             _igen_fb_mm_ucomile_ss
#define _igen_mm_ucomigt_ss             _igen_fb_mm_ucomigt_ss
#define _igen_mm_ucomige_ss             _igen_fb_mm_ucomige_ss
#define _igen_mm_ucomineq_ss            _igen_fb_mm_ucomineq_ss
#define _igen_mm_cvtss_si32             _igen_fb_mm_cvtss_si32
#define _igen_mm_cvt_ss2si              _igen_fb_mm_cvt_ss2si
#define _igen_mm_cvtss_si64             _igen_fb_mm_cvtss_si64
#define _igen_mm_cvtss_f32              _igen_fb_mm_cvtss_f32
#define _igen_mm_cvtps_pi32             _igen_fb_mm_cvtps_pi32
#define _igen_mm_cvt_ps2pi              _igen_fb_mm_cvt_ps2pi
#define _igen_mm_cvttss_si32            _igen_fb_mm_cvttss_si32
#define _igen_mm_cvtt_ss2si             _igen_fb_mm_cvtt_ss2si
#define _igen_mm_cvttss_si64            _igen_fb_mm_cvttss_si64
#define _igen_mm_cvttps_pi32            _igen_fb_mm_cvttps_pi32
#define _igen_mm_cvtt_ps2pi             _igen_fb_mm_cvtt_ps2pi
#define _igen_mm_cvtps_pi16             _igen_fb_mm_cvtps_pi16
#define _igen_mm_cvtps_pi8              _igen_fb_mm_cvtps_pi8
#define _igen_mm_set_ss                 _igen_fb_mm_set_ss
#define _igen_mm_set1_ps                _igen_fb_mm_set1_ps
#define _igen_mm_set_ps1                _igen_fb_mm_set_ps1
#define _igen_mm_set_ps                 _igen_fb_mm_set_ps
#define _igen_mm_setr_ps                _igen_fb_mm_setr_ps
#define _igen_mm_setzero_ps             _igen_fb_mm_setzero_ps
#define _igen_mm_load_ss                _igen_fb_mm_load_ss
#define _igen_mm_load1_ps               _igen_fb_mm_load1_ps
#define _igen_mm_load_ps1               _igen_fb_mm_load_ps1
#define _igen_mm_load_ps                _igen_fb_mm_load_ps
#define _igen_mm_loadu_ps               _igen_fb_mm_loadu_ps
#define _igen_mm_loadr_ps               _igen_fb_mm_loadr_ps
#define _igen_mm_stream_ps              _igen_fb_mm_stream_ps
#define _igen_mm_store_ss               _igen_fb_mm_store_ss
#define _igen_mm_store1_ps              _igen_fb_mm_store1_ps
#define _igen_mm_store_ps1              _igen_fb_mm_store_ps1
#define _igen_mm_store_ps               _igen_fb_mm_store_ps
#define _igen_mm_storeu_ps              _igen_fb_mm_storeu_ps
#define _igen_mm_storer_ps              _igen_fb_mm_storer_ps
#define _igen_mm_move_ss                _igen_fb_mm_move_ss
#define _igen_mm_shuffle_ps             _igen_fb_mm_shuffle_ps
#define _igen_mm_unpackhi_ps            _igen_fb_mm_unpackhi_ps
#define _igen_mm_unpacklo_ps            _igen_fb_mm_unpacklo_ps
#define _igen_mm_movehl_ps              _igen_fb_mm_movehl_ps
#define _igen_mm_movelh_ps              _igen_fb_mm_movelh_ps
#define _igen_mm_movemask_ps            _igen_fb_mm_movemask_ps
#define _igen_mm_cvtepi32_pd            _igen_fb_mm_cvtepi32_pd
#define _igen_mm_cvtsi32_sd             _igen_fb_mm_cvtsi32_sd
#define _igen_mm_cvtsi64_sd             _igen_fb_mm_cvtsi64_sd
#define _igen_mm_cvtsi64x_sd            _igen_fb_mm_cvtsi64x_sd
#define _igen_mm_cvtepi32_ps            _igen_fb_mm_cvtepi32_ps
#define _igen_mm_cvtpi32_pd             _igen_fb_mm_cvtpi32_pd
#define _igen_mm_add_sd                 _igen_fb_mm_add_sd
#define _igen_mm_add_pd                 _igen_fb_mm_add_pd
#define _igen_mm_div_sd                 _igen_fb_mm_div_sd
#define _igen_mm_div_pd                 _igen_fb_mm_div_pd
#define _igen_mm_max_sd                 _igen_fb_mm_max_sd
#define _igen_mm_max_pd                 _igen_fb_mm_max_pd
#define _igen_mm_min_sd                 _igen_fb_mm_min_sd
#define _igen_mm_min_pd                 _igen_fb_mm_min_pd
#define _igen_mm_mul_sd                 _igen_fb_mm_mul_sd
#define _igen_mm_mul_pd                 _igen_fb_mm_mul_pd
#define _igen_mm_sqrt_sd                _igen_fb_mm_sqrt_sd
#define _igen_mm_sqrt_pd                _igen_fb_mm_sqrt_pd
#define _igen_mm_sub_sd                 _igen_fb_mm_sub_sd
#define _igen_mm_sub_pd                 _igen_fb_mm_sub_pd
#define _igen_mm_and_pd                 _igen_fb_mm_and_pd
#define _igen_mm_andnot_pd              _igen_fb_mm_andnot_pd
#define _igen_mm_or_pd                  _igen_fb_mm_or_pd
#define _igen_mm_xor_pd                 _igen_fb_mm_xor_pd
#define _igen_mm_cmpeq_sd               _igen_fb_mm_cmpeq_sd
#define _igen_mm_cmplt_sd               _igen_fb_mm_cmplt_sd
#define _igen_mm_cmple_sd               _igen_fb_mm_cmple_sd
#define _igen_mm_cmpgt_sd               _igen_fb_mm_cmpgt_sd
#define _igen_mm_cmpge_sd               _igen_fb_mm_cmpge_sd
#define _igen_mm_cmpord_sd              _igen_fb_mm_cmpord_sd
#define _igen_mm_cmpunord_sd            _igen_fb_mm_cmpunord_sd
#define _igen_mm_cmpneq_sd              _igen_fb_mm_cmpneq_sd
#define _igen_mm_cmpnlt_sd              _igen_fb_mm_cmpnlt_sd
#define _igen_mm_cmpnle_sd              _igen_fb_mm_cmpnle_sd
#define _igen_mm_cmpngt_sd              _igen_fb_mm_cmpngt_sd
#define _igen_mm_cmpnge_sd              _igen_fb_mm_cmpnge_sd
#define _igen_mm_cmpeq_pd               _igen_fb_mm_cmpeq_pd
#define _igen_mm_cmplt_pd               _igen_fb_mm_cmplt_pd
#define _igen_mm_cmple_pd               _igen_fb_mm_cmple_pd
#define _igen_mm_cmpgt_pd               _igen_fb_mm_cmpgt_pd
#define _igen_mm_cmpge_pd               _igen_fb_mm_cmpge_pd
#define _igen_mm_cmpord_pd              _igen_fb_mm_cmpord_pd
#define _igen_mm_cmpunord_pd            _igen_fb_mm_cmpunord_pd
#define _igen_mm_cmpneq_pd              _igen_fb_mm_cmpneq_pd
#define _igen_mm_cmpnlt_pd              _igen_fb_mm_cmpnlt_pd
#define _igen_mm_cmpnle_pd              _igen_fb_mm_cmpnle_pd
#define _igen_mm_cmpngt_pd              _igen_fb_mm_cmpngt_pd
#define _igen_mm_cmpnge_pd              _igen_fb_mm_cmpnge_pd
#define _igen_mm_comieq_sd              _igen_fb_mm_comieq_sd
#define _igen_mm_comilt_sd              _igen_fb_mm_comilt_sd
#define _igen_mm_comile_sd              _igen_fb_mm_comile_sd
#define _igen_mm_comigt_sd              _igen_fb_mm_comigt_sd
#define _igen_mm_comige_sd              _igen_fb_mm_comige_sd
#define _igen_mm_comineq_sd             _igen_fb_mm_comineq_sd
#define _igen_mm_ucomieq_sd             _igen_fb_mm_ucomieq_sd
#define _igen_mm_ucomilt_sd             _igen_fb_mm_ucomilt_sd
#define _igen_mm_ucomile_sd             _igen_fb_mm_ucomile_sd
#define _igen_mm_ucomigt_sd             _igen_fb_mm_ucomigt_sd
#define _igen_mm_ucomige_sd             _igen_fb_mm_ucomige_sd
#define _igen_mm_ucomineq_sd            _igen_fb_mm_ucomineq_sd
#define _igen_mm_cvtpd_ps               _igen_fb_mm_cvtpd_ps
#define _igen_mm_cvtps_pd               _igen_fb_mm_cvtps_pd
#define _igen_mm_cvtpd_epi32            _igen_fb_mm_cvtpd_epi32
#define _igen_mm_cvtsd_si32             _igen_fb_mm_cvtsd_si32
#define _igen_mm_cvtsd_si64             _igen_fb_mm_cvtsd_si64
#define _igen_mm_cvtsd_si64x            _igen_fb_mm_cvtsd_si64x
#define _igen_mm_cvtsd_ss               _igen_fb_mm_cvtsd_ss
#define _igen_mm_cvtsd_f64              _igen_fb_mm_cvtsd_f64
#define _igen_mm_cvtss_sd               _igen_fb_mm_cvtss_sd
#define _igen_mm_cvttpd_epi32           _igen_fb_mm_cvttpd_epi32
#define _igen_mm_cvttsd_si32            _igen_fb_mm_cvttsd_si32
#define _igen_mm_cvttsd_si64            _igen_fb_mm_cvttsd_si64
#define _igen_mm_cvttsd_si64x           _igen_fb_mm_cvttsd_si64x
#define _igen_mm_cvtps_epi32            _igen_fb_mm_cvtps_epi32
#define _igen_mm_cvttps_epi32           _igen_fb_mm_cvttps_epi32
#define _igen_mm_cvtpd_pi32             _igen_fb_mm_cvtpd_pi32
#define _igen_mm_cvttpd_pi32            _igen_fb_mm_cvttpd_pi32
#define _igen_mm_set_sd                 _igen_fb_mm_set_sd
#define _igen_mm_set1_pd                _igen_fb_mm_set1_pd
#define _igen_mm_set_pd1                _igen_fb_mm_set_pd1
#define _igen_mm_set_pd                 _igen_fb_mm_set_pd
#define _igen_mm_setr_pd                _igen_fb_mm_setr_pd
#define _igen_mm_setzero_pd             _igen_fb_mm_setzero_pd
#define _igen_mm_load_pd                _igen_fb_mm_load_pd
#define _igen_mm_load1_pd               _igen_fb_mm_load1_pd
#define _igen_mm_load_pd1               _igen_fb_mm_load_pd1
#define _igen_mm_loadr_pd               _igen_fb_mm_loadr_pd
#define _igen_mm_loadu_pd               _igen_fb_mm_loadu_pd
#define _igen_mm_load_sd                _igen_fb_mm_load_sd
#define _igen_mm_loadh_pd               _igen_fb_mm_loadh_pd
#define _igen_mm_loadl_pd               _igen_fb_mm_loadl_pd
#define _igen_mm_stream_pd              _igen_fb_mm_stream_pd
#define _igen_mm_store_sd               _igen_fb_mm_store_sd
#define _igen_mm_store1_pd              _igen_fb_mm_store1_pd
#define _igen_mm_store_pd1              _igen_fb_mm_store_pd1
#define _igen_mm_store_pd               _igen_fb_mm_store_pd
#define _igen_mm_storeu_pd              _igen_fb_mm_storeu_pd
#define _igen_mm_storer_pd              _igen_fb_mm_storer_pd
#define _igen_mm_storeh_pd              _igen_fb_mm_storeh_pd
#define _igen_mm_storel_pd              _igen_fb_mm_storel_pd
#define _igen_mm_unpackhi_pd            _igen_fb_mm_unpackhi_pd
#define _igen_mm_unpacklo_pd            _igen_fb_mm_unpacklo_pd
#define _igen_mm_movemask_pd            _igen_fb_mm_movemask_pd
#define _igen_mm_shuffle_pd             _igen_fb_mm_shuffle_pd
#define _igen_mm_move_sd                _igen_fb_mm_move_sd
#define _igen_mm_castpd_ps              _igen_fb_mm_castpd_ps
#define _igen_mm_castpd_si128           _igen_fb_mm_castpd_si128
#define _igen_mm_castps_pd              _igen_fb_mm_castps_pd
#define _igen_mm_castps_si128           _igen_fb_mm_castps_si128
#define _igen_mm_castsi128_pd           _igen_fb_mm_castsi128_pd
#define _igen_mm_castsi128_ps           _igen_fb_mm_castsi128_ps
#define _igen_cvtsh_ss                  _igen_fb_cvtsh_ss
#define _igen_cvtss_sh                  _igen_fb_cvtss_sh
#define _igen_mm_cvtph_ps               _igen_fb_mm_cvtph_ps
#define _igen_mm_cvtps_ph               _igen_fb_mm_cvtps_ph
#define _igen_mm_addsub_ps              _igen_fb_mm_addsub_ps
#define _igen_mm_addsub_pd              _igen_fb_mm_addsub_pd
#define _igen_mm_hadd_pd                _igen_fb_mm_hadd_pd
#define _igen_mm_hadd_ps                _igen_fb_mm_hadd_ps
#define _igen_mm_hsub_pd                _igen_fb_mm_hsub_pd
#define _igen_mm_hsub_ps                _igen_fb_mm_hsub_ps
#define _igen_mm_movedup_pd             _igen_fb_mm_movedup_pd
#define _igen_mm_loaddup_pd             _igen_fb_mm_loaddup_pd
#define _igen_mm_movehdup_ps            _igen_fb_mm_movehdup_ps
#define _igen_mm_moveldup_ps            _igen_fb_mm_moveldup_ps
#define _igen_mm_blend_pd               _igen_fb_mm_blend_pd
#define _igen_mm_blend_ps               _igen_fb_mm_blend_ps
#define _igen_mm_blendv_pd              _igen_fb_mm_blendv_pd
#define _igen_mm_blendv_ps              _igen_fb_mm_blendv_ps
#define _igen_mm_dp_pd                  _igen_fb_mm_dp_pd
#define _igen_mm_dp_ps                  _igen_fb_mm_dp_ps
#define _igen_mm_extract_ps             _igen_fb_mm_extract_ps
#define _igen_mm_insert_ps              _igen_fb_mm_insert_ps
#define _igen_mm_round_pd               _igen_fb_mm_round_pd
#define _igen_mm_floor_pd               _igen_fb_mm_floor_pd
#define _igen_mm_ceil_pd                _igen_fb_mm_ceil_pd
#define _igen_mm_round_ps               _igen_fb_mm_round_ps
#define _igen_mm_floor_ps               _igen_fb_mm_floor_ps
#define _igen_mm_ceil_ps                _igen_fb_mm_ceil_ps
#define _igen_mm_round_sd               _igen_fb_mm_round_sd
#define _igen_mm_floor_sd               _igen_fb_mm_floor_sd
#define _igen_mm_ceil_sd                _igen_fb_mm_ceil_sd
#define _igen_mm_round_ss               _igen_fb_mm_round_ss
#define _igen_mm_floor_ss               _igen_fb_mm_floor_ss
#define _igen_mm_ceil_ss                _igen_fb_mm_ceil_ss
#define _igen_mm256_add_pd              _igen_fb_mm256_add_pd
#define _igen_mm256_add_ps              _igen_fb_mm256_add_ps
#define _igen_mm256_addsub_pd           _igen_fb_mm256_addsub_pd
#define _igen_mm256_addsub_ps           _igen_fb_mm256_addsub_ps
#define _igen_mm256_and_pd              _igen_fb_mm256_and_pd
#define _igen_mm256_and_ps              _igen_fb_mm256_and_ps
#define _igen_mm256_andnot_pd           _igen_fb_mm256_andnot_pd
#define _igen_mm256_andnot_ps           _igen_fb_mm256_andnot_ps
#define _igen_mm256_blend_pd            _igen_fb_mm256_blend_pd
#define _igen_mm256_blend_ps            _igen_fb_mm256_blend_ps
#define _igen_mm256_blendv_pd           _igen_fb_mm256_blendv_pd
#define _igen_mm256_blendv_ps           _igen_fb_mm256_blendv_ps
#define _igen_mm256_div_pd              _igen_fb_mm256_div_pd
#define _igen_mm256_div_ps              _igen_fb_mm256_div_ps
#define _igen_mm256_dp_ps               _igen_fb_mm256_dp_ps
#define _igen_mm256_hadd_pd             _igen_fb_mm256_hadd_pd
#define _igen_mm256_hadd_ps             _igen_fb_mm256_hadd_ps
#define _igen_mm256_hsub_pd             _igen_fb_mm256_hsub_pd
#define _igen_mm256_hsub_ps             _igen_fb_mm256_hsub_ps
#define _igen_mm256_max_pd              _igen_fb_mm256_max_pd
#define _igen_mm256_max_ps              _igen_fb_mm256_max_ps
#define _igen_mm256_min_pd              _igen_fb_mm256_min_pd
#define _igen_mm256_min_ps              _igen_fb_mm256_min_ps
#define _igen_mm256_mul_pd              _igen_fb_mm256_mul_pd
#define _igen_mm256_mul_ps              _igen_fb_mm256_mul_ps
#define _igen_mm256_or_pd               _igen_fb_mm256_or_pd
#define _igen_mm256_or_ps               _igen_fb_mm256_or_ps
#define _igen_mm256_shuffle_pd          _igen_fb_mm256_shuffle_pd
#define _igen_mm256_shuffle_ps          _igen_fb_mm256_shuffle_ps
#define _igen_mm256_sub_pd              _igen_fb_mm256_sub_pd
#define _igen_mm256_sub_ps              _igen_fb_mm256_sub_ps
#define _igen_mm256_xor_pd              _igen_fb_mm256_xor_pd
#define _igen_mm256_xor_ps              _igen_fb_mm256_xor_ps
#define _igen_mm_cmp_pd                 _igen_fb_mm_cmp_pd
#define _igen_mm256_cmp_pd              _igen_fb_mm256_cmp_pd
#define _igen_mm_cmp_ps                 _igen_fb_mm_cmp_ps
#define _igen_mm256_cmp_ps              _igen_fb_mm256_cmp_ps
#define _igen_mm_cmp_sd                 _igen_fb_mm_cmp_sd
#define _igen_mm_cmp_ss                 _igen_fb_mm_cmp_ss
#define _igen_mm256_cvtepi32_pd         _igen_fb_mm256_cvtepi32_pd
#define _igen_mm256_cvtepi32_ps         _igen_fb_mm256_cvtepi32_ps
#define _igen_mm256_cvtpd_ps            _igen_fb_mm256_cvtpd_ps
#define _igen_mm256_cvtps_epi32         _igen_fb_mm256_cvtps_epi32
#define _igen_mm256_cvtps_pd            _igen_fb_mm256_cvtps_pd
#define _igen_mm256_cvttpd_epi32        _igen_fb_mm256_cvttpd_epi32
#define _igen_mm256_cvtpd_epi32         _igen_fb_mm256_cvtpd_epi32
#define _igen_mm256_cvttps_epi32        _igen_fb_mm256_cvttps_epi32
#define _igen_mm256_extractf128_ps      _igen_fb_mm256_extractf128_ps
#define _igen_mm256_extractf128_pd      _igen_fb_mm256_extractf128_pd
#define _igen_mm256_permutevar_ps       _igen_fb_mm256_permutevar_ps
#define _igen_mm_permutevar_ps          _igen_fb_mm_permutevar_ps
#define _igen_mm256_permute_ps          _igen_fb_mm256_permute_ps
#define _igen_mm_permute_ps             _igen_fb_mm_permute_ps
#define _igen_mm256_permutevar_pd       _igen_fb_mm256_permutevar_pd
#define _igen_mm_permutevar_pd          _igen_fb_mm_permutevar_pd
#define _igen_mm256_permute_pd          _igen_fb_mm256_permute_pd
#define _igen_mm_permute_pd             _igen_fb_mm_permute_pd
#define _igen_mm256_permute2f128_ps     _igen_fb_mm256_permute2f128_ps
#define _igen_mm256_permute2f128_pd     _igen_fb_mm256_permute2f128_pd
#define _igen_mm256_broadcast_ss        _igen_fb_mm256_broadcast_ss
#define _igen_mm_broadcast_ss           _igen_fb_mm_broadcast_ss
#define _igen_mm256_broadcast_sd        _igen_fb_mm256_broadcast_sd
#define _igen_mm256_broadcast_ps        _igen_fb_mm256_broadcast_ps
#define _igen_mm256_broadcast_pd        _igen_fb_mm256_broadcast_pd
#define _igen_mm256_insertf128_ps       _igen_fb_mm256_insertf128_ps
#define _igen_mm256_insertf128_pd       _igen_fb_mm256_insertf128_pd
#define _igen_mm256_load_pd             _igen_fb_mm256_load_pd
#define _igen_mm256_store_pd            _igen_fb_mm256_store_pd
#define _igen_mm256_load_ps             _igen_fb_mm256_load_ps
#define _igen_mm256_store_ps            _igen_fb_mm256_store_ps
#define _igen_mm256_loadu_pd            _igen_fb_mm256_loadu_pd
#define _igen_mm256_storeu_pd           _igen_fb_mm256_storeu_pd
#define _igen_mm256_loadu_ps            _igen_fb_mm256_loadu_ps
#define _igen_mm256_storeu_ps           _igen_fb_mm256_storeu_ps
#define _igen_mm256_maskload_pd         _igen_fb_mm256_maskload_pd
#define _igen_mm256_maskstore_pd        _igen_fb_mm256_maskstore_pd
#define _igen_mm_maskload_pd            _igen_fb_mm_maskload_pd
#define _igen_mm_maskstore_pd           _igen_fb_mm_maskstore_pd
#define _igen_mm256_maskload_ps         _igen_fb_mm256_maskload_ps
#define _igen_mm256_maskstore_ps        _igen_fb_mm256_maskstore_ps
#define _igen_mm_maskload_ps            _igen_fb_mm_maskload_ps
#define _igen_mm_maskstore_ps           _igen_fb_mm_maskstore_ps
#define _igen_mm256_movehdup_ps         _igen_fb_mm256_movehdup_ps
#define _igen_mm256_moveldup_ps         _igen_fb_mm256_moveldup_ps
#define _igen_mm256_movedup_pd          _igen_fb_mm256_movedup_pd
#define _igen_mm256_stream_pd           _igen_fb_mm256_stream_pd
#define _igen_mm256_stream_ps           _igen_fb_mm256_stream_ps
#define _igen_mm256_rcp_ps              _igen_fb_mm256_rcp_ps
#define _igen_mm256_rsqrt_ps            _igen_fb_mm256_rsqrt_ps
#define _igen_mm256_sqrt_pd             _igen_fb_mm256_sqrt_pd
#define _igen_mm256_sqrt_ps             _igen_fb_mm256_sqrt_ps
#define _igen_mm256_round_pd            _igen_fb_mm256_round_pd
#define _igen_mm256_round_ps            _igen_fb_mm256_round_ps
#define _igen_mm256_unpackhi_pd         _igen_fb_mm256_unpackhi_pd
#define _igen_mm256_unpackhi_ps         _igen_fb_mm256_unpackhi_ps
#define _igen_mm256_unpacklo_pd         _igen_fb_mm256_unpacklo_pd
#define _igen_mm256_unpacklo_ps         _igen_fb_mm256_unpacklo_ps
#define _igen_mm256_testz_pd            _igen_fb_mm256_testz_pd
#define _igen_mm256_testc_pd            _igen_fb_mm256_testc_pd
#define _igen_mm256_testnzc_pd          _igen_fb_mm256_testnzc_pd
#define _igen_mm_testz_pd               _igen_fb_mm_testz_pd
#define _igen_mm_testc_pd               _igen_fb_mm_testc_pd
#define _igen_mm_testnzc_pd             _igen_fb_mm_testnzc_pd
#define _igen_mm256_testz_ps            _igen_fb_mm256_testz_ps
#define _igen_mm256_testc_ps            _igen_fb_mm256_testc_ps
#define _igen_mm256_testnzc_ps          _igen_fb_mm256_testnzc_ps
#define _igen_mm_testz_ps               _igen_fb_mm_testz_ps
#define _igen_mm_testc_ps               _igen_fb_mm_testc_ps
#define _igen_mm_testnzc_ps             _igen_fb_mm_testnzc_ps
#define _igen_mm256_movemask_pd         _igen_fb_mm256_movemask_pd
#define _igen_mm256_movemask_ps         _igen_fb_mm256_movemask_ps
#define _igen_mm256_setzero_pd          _igen_fb_mm256_setzero_pd
#define _igen_mm256_setzero_ps          _igen_fb_mm256_setzero_ps
#define _igen_mm256_set_pd              _igen_fb_mm256_set_pd
#define _igen_mm256_set_ps              _igen_fb_mm256_set_ps
#define _igen_mm256_setr_pd             _igen_fb_mm256_setr_pd
#define _igen_mm256_setr_ps             _igen_fb_mm256_setr_ps
#define _igen_mm256_set1_pd             _igen_fb_mm256_set1_pd
#define _igen_mm256_set1_ps             _igen_fb_mm256_set1_ps
#define _igen_mm256_castpd_ps           _igen_fb_mm256_castpd_ps
#define _igen_mm256_castps_pd           _igen_fb_mm256_castps_pd
#define _igen_mm256_castps_si256        _igen_fb_mm256_castps_si256
#define _igen_mm256_castpd_si256        _igen_fb_mm256_castpd_si256
#define _igen_mm256_castsi256_ps        _igen_fb_mm256_castsi256_ps
#define _igen_mm256_castsi256_pd        _igen_fb_mm256_castsi256_pd
#define _igen_mm256_castps256_ps128     _igen_fb_mm256_castps256_ps128
#define _igen_mm256_castpd256_pd128     _igen_fb_mm256_castpd256_pd128
#define _igen_mm256_castps128_ps256     _igen_fb_mm256_castps128_ps256
#define _igen_mm256_castpd128_pd256     _igen_fb_mm256_castpd128_pd256
#define _igen_mm256_zextps128_ps256     _igen_fb_mm256_zextps128_ps256
#define _igen_mm256_zextpd128_pd256     _igen_fb_mm256_zextpd128_pd256
#define _igen_mm256_floor_ps            _igen_fb_mm256_floor_ps
#define _igen_mm256_ceil_ps             _igen_fb_mm256_ceil_ps
#define _igen_mm256_floor_pd            _igen_fb_mm256_floor_pd
#define _igen_mm256_ceil_pd             _igen_fb_mm256_ceil_pd
#define _igen_mm_undefined_ps           _igen_fb_mm_undefined_ps
#define _igen_mm_undefined_pd           _igen_fb_mm_undefined_pd
#define _igen_mm256_undefined_ps        _igen_fb_mm256_undefined_ps
#define _igen_mm256_undefined_pd        _igen_fb_mm256_undefined_pd
#define _igen_mm256_set_m128            _igen_fb_mm256_set_m128
#define _igen_mm256_set_m128d           _igen_fb_mm256_set_m128d
#define _igen_mm256_setr_m128           _igen_fb_mm256_setr_m128
#define _igen_mm256_setr_m128d          _igen_fb_mm256_setr_m128d
#define _igen_mm256_loadu2_m128         _igen_fb_mm256_loadu2_m128
#define _igen_mm256_loadu2_m128d        _igen_fb_mm256_loadu2_m128d
#define _igen_mm256_storeu2_m128        _igen_fb_mm256_storeu2_m128
#define _igen_mm256_storeu2_m128d       _igen_fb_mm256_storeu2_m128d
#define _igen_mm_broadcastsd_pd         _igen_fb_mm_broadcastsd_pd
#define _igen_mm256_broadcastsd_pd      _igen_fb_mm256_broadcastsd_pd
#define _igen_mm_broadcastss_ps         _igen_fb_mm_broadcastss_ps
#define _igen_mm256_broadcastss_ps      _igen_fb_mm256_broadcastss_ps
#define _igen_mm_i32gather_pd           _igen_fb_mm_i32gather_pd
#define _igen_mm256_i32gather_pd        _igen_fb_mm256_i32gather_pd
#define _igen_mm_i32gather_ps           _igen_fb_mm_i32gather_ps
#define _igen_mm256_i32gather_ps        _igen_fb_mm256_i32gather_ps
#define _igen_mm_i64gather_pd           _igen_fb_mm_i64gather_pd
#define _igen_mm256_i64gather_pd        _igen_fb_mm256_i64gather_pd
#define _igen_mm_i64gather_ps           _igen_fb_mm_i64gather_ps
#define _igen_mm256_i64gather_ps        _igen_fb_mm256_i64gather_ps
#define _igen_mm_mask_i32gather_pd      _igen_fb_mm_mask_i32gather_pd
#define _igen_mm256_mask_i32gather_pd   _igen_fb_mm256_mask_i32gather_p
#define _igen_mm_mask_i32gather_ps      _igen_fb_mm_mask_i32gather_ps
#define _igen_mm256_mask_i32gather_ps   _igen_fb_mm256_mask_i32gather_p
#define _igen_mm_mask_i64gather_pd      _igen_fb_mm_mask_i64gather_pd
#define _igen_mm256_mask_i64gather_pd   _igen_fb_mm256_mask_i64gather_p
#define _igen_mm_mask_i64gather_ps      _igen_fb_mm_mask_i64gather_ps
#define _igen_mm256_mask_i64gather_ps   _igen_fb_mm256_mask_i64gather_p
#define _igen_mm256_permute4x64_pd      _igen_fb_mm256_permute4x64_pd
#define _igen_mm256_permutevar8x32_ps   _igen_fb_mm256_permutevar8x32_p
#define _igen_mm_fmadd_pd               _igen_fb_mm_fmadd_pd
#define _igen_mm256_fmadd_pd            _igen_fb_mm256_fmadd_pd
#define _igen_mm_fmadd_ps               _igen_fb_mm_fmadd_ps
#define _igen_mm256_fmadd_ps            _igen_fb_mm256_fmadd_ps
#define _igen_mm_fmadd_sd               _igen_fb_mm_fmadd_sd
#define _igen_mm_fmadd_ss               _igen_fb_mm_fmadd_ss
#define _igen_mm_fmaddsub_pd            _igen_fb_mm_fmaddsub_pd
#define _igen_mm256_fmaddsub_pd         _igen_fb_mm256_fmaddsub_pd
#define _igen_mm_fmaddsub_ps            _igen_fb_mm_fmaddsub_ps
#define _igen_mm256_fmaddsub_ps         _igen_fb_mm256_fmaddsub_ps
#define _igen_mm_fmsub_pd               _igen_fb_mm_fmsub_pd
#define _igen_mm256_fmsub_pd            _igen_fb_mm256_fmsub_pd
#define _igen_mm_fmsub_ps               _igen_fb_mm_fmsub_ps
#define _igen_mm256_fmsub_ps            _igen_fb_mm256_fmsub_ps
#define _igen_mm_fmsub_sd               _igen_fb_mm_fmsub_sd
#define _igen_mm_fmsub_ss               _igen_fb_mm_fmsub_ss
#define _igen_mm_fmsubadd_pd            _igen_fb_mm_fmsubadd_pd
#define _igen_mm256_fmsubadd_pd         _igen_fb_mm256_fmsubadd_pd
#define _igen_mm_fmsubadd_ps            _igen_fb_mm_fmsubadd_ps
#define _igen_mm256_fmsubadd_ps         _igen_fb_mm256_fmsubadd_ps
#define _igen_mm_fnmadd_pd              _igen_fb_mm_fnmadd_pd
#define _igen_mm256_fnmadd_pd           _igen_fb_mm256_fnmadd_pd
#define _igen_mm_fnmadd_ps              _igen_fb_mm_fnmadd_ps
#define _igen_mm256_fnmadd_ps           _igen_fb_mm256_fnmadd_ps
#define _igen_mm_fnmadd_sd              _igen_fb_mm_fnmadd_sd
#define _igen_mm_fnmadd_ss              _igen_fb_mm_fnmadd_ss
#define _igen_mm_fnmsub_pd              _igen_fb_mm_fnmsub_pd
#define _igen_mm256_fnmsub_pd           _igen_fb_mm256_fnmsub_pd
#define _igen_mm_fnmsub_ps              _igen_fb_mm_fnmsub_ps
#define _igen_mm256_fnmsub_ps           _igen_fb_mm256_fnmsub_ps
#define _igen_mm_fnmsub_sd              _igen_fb_mm_fnmsub_sd
#define _igen_mm_fnmsub_ss              _igen_fb_mm_fnmsub_ss
#define _igen_castf32_u32               _igen_fb_castf32_u32
#define _igen_castf64_u64               _igen_fb_castf64_u64
#define _igen_castu32_f32               _igen_fb_castu32_f32
#define _igen_castu64_f64               _igen_fb_castu64_f64
#define _igen_mm_acos_pd                _igen_fb_mm_acos_pd
#define _igen_mm_acos_ps                _igen_fb_mm_acos_ps
#define _igen_mm_acosh_pd               _igen_fb_mm_acosh_pd
#define _igen_mm_acosh_ps               _igen_fb_mm_acosh_ps
#define _igen_mm_asin_pd                _igen_fb_mm_asin_pd
#define _igen_mm_asin_ps                _igen_fb_mm_asin_ps
#define _igen_mm_asinh_pd               _igen_fb_mm_asinh_pd
#define _igen_mm_asinh_ps               _igen_fb_mm_asinh_ps
#define _igen_mm_atan_pd                _igen_fb_mm_atan_pd
#define _igen_mm_atan_ps                _igen_fb_mm_atan_ps
#define _igen_mm_atan2_pd               _igen_fb_mm_atan2_pd
#define _igen_mm_atan2_ps               _igen_fb_mm_atan2_ps
#define _igen_mm_atanh_pd               _igen_fb_mm_atanh_pd
#define _igen_mm_atanh_ps               _igen_fb_mm_atanh_ps
#define _igen_mm_cbrt_pd                _igen_fb_mm_cbrt_pd
#define _igen_mm_cbrt_ps                _igen_fb_mm_cbrt_ps
#define _igen_mm_cdfnorm_pd             _igen_fb_mm_cdfnorm_pd
#define _igen_mm_cdfnorm_ps             _igen_fb_mm_cdfnorm_ps
#define _igen_mm_cdfnorminv_pd          _igen_fb_mm_cdfnorminv_pd
#define _igen_mm_cdfnorminv_ps          _igen_fb_mm_cdfnorminv_ps
#define _igen_mm_cexp_ps                _igen_fb_mm_cexp_ps
#define _igen_mm_clog_ps                _igen_fb_mm_clog_ps
#define _igen_mm_cos_pd                 _igen_fb_mm_cos_pd
#define _igen_mm_cos_ps                 _igen_fb_mm_cos_ps
#define _igen_mm_cosd_pd                _igen_fb_mm_cosd_pd
#define _igen_mm_cosd_ps                _igen_fb_mm_cosd_ps
#define _igen_mm_cosh_pd                _igen_fb_mm_cosh_pd
#define _igen_mm_cosh_ps                _igen_fb_mm_cosh_ps
#define _igen_mm_csqrt_ps               _igen_fb_mm_csqrt_ps
#define _igen_mm_erf_pd                 _igen_fb_mm_erf_pd
#define _igen_mm_erf_ps                 _igen_fb_mm_erf_ps
#define _igen_mm_erfc_pd                _igen_fb_mm_erfc_pd
#define _igen_mm_erfc_ps                _igen_fb_mm_erfc_ps
#define _igen_mm_erfcinv_pd             _igen_fb_mm_erfcinv_pd
#define _igen_mm_erfcinv_ps             _igen_fb_mm_erfcinv_ps
#define _igen_mm_erfinv_pd              _igen_fb_mm_erfinv_pd
#define _igen_mm_erfinv_ps              _igen_fb_mm_erfinv_ps
#define _igen_mm_exp_pd                 _igen_fb_mm_exp_pd
#define _igen_mm_exp_ps                 _igen_fb_mm_exp_ps
#define _igen_mm_exp10_pd               _igen_fb_mm_exp10_pd
#define _igen_mm_exp10_ps               _igen_fb_mm_exp10_ps
#define _igen_mm_exp2_pd                _igen_fb_mm_exp2_pd
#define _igen_mm_exp2_ps                _igen_fb_mm_exp2_ps
#define _igen_mm_expm1_pd               _igen_fb_mm_expm1_pd
#define _igen_mm_expm1_ps               _igen_fb_mm_expm1_ps
#define _igen_mm_hypot_pd               _igen_fb_mm_hypot_pd
#define _igen_mm_hypot_ps               _igen_fb_mm_hypot_ps
#define _igen_mm_invcbrt_pd             _igen_fb_mm_invcbrt_pd
#define _igen_mm_invcbrt_ps             _igen_fb_mm_invcbrt_ps
#define _igen_mm_invsqrt_pd             _igen_fb_mm_invsqrt_pd
#define _igen_mm_invsqrt_ps             _igen_fb_mm_invsqrt_ps
#define _igen_mm_log_pd                 _igen_fb_mm_log_pd
#define _igen_mm_log_ps                 _igen_fb_mm_log_ps
#define _igen_mm_log10_pd               _igen_fb_mm_log10_pd
#define _igen_mm_log10_ps               _igen_fb_mm_log10_ps
#define _igen_mm_log1p_pd               _igen_fb_mm_log1p_pd
#define _igen_mm_log1p_ps               _igen_fb_mm_log1p_ps
#define _igen_mm_log2_pd                _igen_fb_mm_log2_pd
#define _igen_mm_log2_ps                _igen_fb_mm_log2_ps
#define _igen_mm_logb_pd                _igen_fb_mm_logb_pd
#define _igen_mm_logb_ps                _igen_fb_mm_logb_ps
#define _igen_mm_pow_pd                 _igen_fb_mm_pow_pd
#define _igen_mm_pow_ps                 _igen_fb_mm_pow_ps
#define _igen_mm_sin_pd                 _igen_fb_mm_sin_pd
#define _igen_mm_sin_ps                 _igen_fb_mm_sin_ps
#define _igen_mm_sincos_pd              _igen_fb_mm_sincos_pd
#define _igen_mm_sincos_ps              _igen_fb_mm_sincos_ps
#define _igen_mm_sind_pd                _igen_fb_mm_sind_pd
#define _igen_mm_sind_ps                _igen_fb_mm_sind_ps
#define _igen_mm_sinh_pd                _igen_fb_mm_sinh_pd
#define _igen_mm_sinh_ps                _igen_fb_mm_sinh_ps
#define _igen_mm_svml_ceil_pd           _igen_fb_mm_svml_ceil_pd
#define _igen_mm_svml_ceil_ps           _igen_fb_mm_svml_ceil_ps
#define _igen_mm_svml_floor_pd          _igen_fb_mm_svml_floor_pd
#define _igen_mm_svml_floor_ps          _igen_fb_mm_svml_floor_ps
#define _igen_mm_svml_round_pd          _igen_fb_mm_svml_round_pd
#define _igen_mm_svml_round_ps          _igen_fb_mm_svml_round_ps
#define _igen_mm_svml_sqrt_pd           _igen_fb_mm_svml_sqrt_pd
#define _igen_mm_svml_sqrt_ps           _igen_fb_mm_svml_sqrt_ps
#define _igen_mm_tan_pd                 _igen_fb_mm_tan_pd
#define _igen_mm_tan_ps                 _igen_fb_mm_tan_ps
#define _igen_mm_tand_pd                _igen_fb_mm_tand_pd
#define _igen_mm_tand_ps                _igen_fb_mm_tand_ps
#define _igen_mm_tanh_pd                _igen_fb_mm_tanh_pd
#define _igen_mm_tanh_ps                _igen_fb_mm_tanh_ps
#define _igen_mm_trunc_pd               _igen_fb_mm_trunc_pd
#define _igen_mm_trunc_ps               _igen_fb_mm_trunc_ps
#define _igen_mm256_acos_pd             _igen_fb_mm256_acos_pd
#define _igen_mm256_acos_ps             _igen_fb_mm256_acos_ps
#define _igen_mm256_acosh_pd            _igen_fb_mm256_acosh_pd
#define _igen_mm256_acosh_ps            _igen_fb_mm256_acosh_ps
#define _igen_mm256_asin_pd             _igen_fb_mm256_asin_pd
#define _igen_mm256_asin_ps             _igen_fb_mm256_asin_ps
#define _igen_mm256_asinh_pd            _igen_fb_mm256_asinh_pd
#define _igen_mm256_asinh_ps            _igen_fb_mm256_asinh_ps
#define _igen_mm256_atan_pd             _igen_fb_mm256_atan_pd
#define _igen_mm256_atan_ps             _igen_fb_mm256_atan_ps
#define _igen_mm256_atan2_pd            _igen_fb_mm256_atan2_pd
#define _igen_mm256_atan2_ps            _igen_fb_mm256_atan2_ps
#define _igen_mm256_atanh_pd            _igen_fb_mm256_atanh_pd
#define _igen_mm256_atanh_ps            _igen_fb_mm256_atanh_ps
#define _igen_mm256_cbrt_pd             _igen_fb_mm256_cbrt_pd
#define _igen_mm256_cbrt_ps             _igen_fb_mm256_cbrt_ps
#define _igen_mm256_cdfnorm_pd          _igen_fb_mm256_cdfnorm_pd
#define _igen_mm256_cdfnorm_ps          _igen_fb_mm256_cdfnorm_ps
#define _igen_mm256_cdfnorminv_pd       _igen_fb_mm256_cdfnorminv_pd
#define _igen_mm256_cdfnorminv_ps       _igen_fb_mm256_cdfnorminv_ps
#define _igen_mm256_cexp_ps             _igen_fb_mm256_cexp_ps
#define _igen_mm256_clog_ps             _igen_fb_mm256_clog_ps
#define _igen_mm256_cos_pd              _igen_fb_mm256_cos_pd
#define _igen_mm256_cos_ps              _igen_fb_mm256_cos_ps
#define _igen_mm256_cosd_pd             _igen_fb_mm256_cosd_pd
#define _igen_mm256_cosd_ps             _igen_fb_mm256_cosd_ps
#define _igen_mm256_cosh_pd             _igen_fb_mm256_cosh_pd
#define _igen_mm256_cosh_ps             _igen_fb_mm256_cosh_ps
#define _igen_mm256_csqrt_ps            _igen_fb_mm256_csqrt_ps
#define _igen_mm256_erf_pd              _igen_fb_mm256_erf_pd
#define _igen_mm256_erf_ps              _igen_fb_mm256_erf_ps
#define _igen_mm256_erfc_pd             _igen_fb_mm256_erfc_pd
#define _igen_mm256_erfc_ps             _igen_fb_mm256_erfc_ps
#define _igen_mm256_erfcinv_pd          _igen_fb_mm256_erfcinv_pd
#define _igen_mm256_erfcinv_ps          _igen_fb_mm256_erfcinv_ps
#define _igen_mm256_erfinv_pd           _igen_fb_mm256_erfinv_pd
#define _igen_mm256_erfinv_ps           _igen_fb_mm256_erfinv_ps
#define _igen_mm256_exp_pd              _igen_fb_mm256_exp_pd
#define _igen_mm256_exp_ps              _igen_fb_mm256_exp_ps
#define _igen_mm256_exp10_pd            _igen_fb_mm256_exp10_pd
#define _igen_mm256_exp10_ps            _igen_fb_mm256_exp10_ps
#define _igen_mm256_exp2_pd             _igen_fb_mm256_exp2_pd
#define _igen_mm256_exp2_ps             _igen_fb_mm256_exp2_ps
#define _igen_mm256_expm1_pd            _igen_fb_mm256_expm1_pd
#define _igen_mm256_expm1_ps            _igen_fb_mm256_expm1_ps
#define _igen_mm256_hypot_pd            _igen_fb_mm256_hypot_pd
#define _igen_mm256_hypot_ps            _igen_fb_mm256_hypot_ps
#define _igen_mm256_invcbrt_pd          _igen_fb_mm256_invcbrt_pd
#define _igen_mm256_invcbrt_ps          _igen_fb_mm256_invcbrt_ps
#define _igen_mm256_invsqrt_pd          _igen_fb_mm256_invsqrt_pd
#define _igen_mm256_invsqrt_ps          _igen_fb_mm256_invsqrt_ps
#define _igen_mm256_log_pd              _igen_fb_mm256_log_pd
#define _igen_mm256_log_ps              _igen_fb_mm256_log_ps
#define _igen_mm256_log10_pd            _igen_fb_mm256_log10_pd
#define _igen_mm256_log10_ps            _igen_fb_mm256_log10_ps
#define _igen_mm256_log1p_pd            _igen_fb_mm256_log1p_pd
#define _igen_mm256_log1p_ps            _igen_fb_mm256_log1p_ps
#define _igen_mm256_log2_pd             _igen_fb_mm256_log2_pd
#define _igen_mm256_log2_ps             _igen_fb_mm256_log2_ps
#define _igen_mm256_logb_pd             _igen_fb_mm256_logb_pd
#define _igen_mm256_logb_ps             _igen_fb_mm256_logb_ps
#define _igen_mm256_pow_pd              _igen_fb_mm256_pow_pd
#define _igen_mm256_pow_ps              _igen_fb_mm256_pow_ps
#define _igen_mm256_sin_pd              _igen_fb_mm256_sin_pd
#define _igen_mm256_sin_ps              _igen_fb_mm256_sin_ps
#define _igen_mm256_sincos_pd           _igen_fb_mm256_sincos_pd
#define _igen_mm256_sincos_ps           _igen_fb_mm256_sincos_ps
#define _igen_mm256_sind_pd             _igen_fb_mm256_sind_pd
#define _igen_mm256_sind_ps             _igen_fb_mm256_sind_ps
#define _igen_mm256_sinh_pd             _igen_fb_mm256_sinh_pd
#define _igen_mm256_sinh_ps             _igen_fb_mm256_sinh_ps
#define _igen_mm256_svml_ceil_pd        _igen_fb_mm256_svml_ceil_pd
#define _igen_mm256_svml_ceil_ps        _igen_fb_mm256_svml_ceil_ps
#define _igen_mm256_svml_floor_pd       _igen_fb_mm256_svml_floor_pd
#define _igen_mm256_svml_floor_ps       _igen_fb_mm256_svml_floor_ps
#define _igen_mm256_svml_round_pd       _igen_fb_mm256_svml_round_pd
#define _igen_mm256_svml_round_ps       _igen_fb_mm256_svml_round_ps
#define _igen_mm256_svml_sqrt_pd        _igen_fb_mm256_svml_sqrt_pd
#define _igen_mm256_svml_sqrt_ps        _igen_fb_mm256_svml_sqrt_ps
#define _igen_mm256_tan_pd              _igen_fb_mm256_tan_pd
#define _igen_mm256_tan_ps              _igen_fb_mm256_tan_ps
#define _igen_mm256_tand_pd             _igen_fb_mm256_tand_pd
#define _igen_mm256_tand_ps             _igen_fb_mm256_tand_ps
#define _igen_mm256_tanh_pd             _igen_fb_mm256_tanh_pd
#define _igen_mm256_tanh_ps             _igen_fb_mm256_tanh_ps
#define _igen_mm256_trunc_pd            _igen_fb_mm256_trunc_pd
#define _igen_mm256_trunc_ps            _igen_fb_mm256_trunc_ps
#define _igen_mm256_cvtph_ps            _igen_fb_mm256_cvtph_ps
#define _igen_mm256_cvtps_ph            _igen_fb_mm256_cvtps_ph
#define _igen_mm256_cvtss_f32           _igen_fb_mm256_cvtss_f32
#define _igen_mm256_cvtsd_f64           _igen_fb_mm256_cvtsd_f64
#define _igen_mm512_acos_pd             _igen_fb_mm512_acos_pd
#define _igen_mm512_mask_acos_pd        _igen_fb_mm512_mask_acos_pd
#define _igen_mm512_acos_ps             _igen_fb_mm512_acos_ps
#define _igen_mm512_mask_acos_ps        _igen_fb_mm512_mask_acos_ps
#define _igen_mm512_acosh_pd            _igen_fb_mm512_acosh_pd
#define _igen_mm512_mask_acosh_pd       _igen_fb_mm512_mask_acosh_pd
#define _igen_mm512_acosh_ps            _igen_fb_mm512_acosh_ps
#define _igen_mm512_mask_acosh_ps       _igen_fb_mm512_mask_acosh_ps
#define _igen_mm512_asin_pd             _igen_fb_mm512_asin_pd
#define _igen_mm512_mask_asin_pd        _igen_fb_mm512_mask_asin_pd
#define _igen_mm512_asin_ps             _igen_fb_mm512_asin_ps
#define _igen_mm512_mask_asin_ps        _igen_fb_mm512_mask_asin_ps
#define _igen_mm512_asinh_pd            _igen_fb_mm512_asinh_pd
#define _igen_mm512_mask_asinh_pd       _igen_fb_mm512_mask_asinh_pd
#define _igen_mm512_asinh_ps            _igen_fb_mm512_asinh_ps
#define _igen_mm512_mask_asinh_ps       _igen_fb_mm512_mask_asinh_ps
#define _igen_mm512_atan2_pd            _igen_fb_mm512_atan2_pd
#define _igen_mm512_mask_atan2_pd       _igen_fb_mm512_mask_atan2_pd
#define _igen_mm512_atan2_ps            _igen_fb_mm512_atan2_ps
#define _igen_mm512_mask_atan2_ps       _igen_fb_mm512_mask_atan2_ps
#define _igen_mm512_atan_pd             _igen_fb_mm512_atan_pd
#define _igen_mm512_mask_atan_pd        _igen_fb_mm512_mask_atan_pd
#define _igen_mm512_atan_ps             _igen_fb_mm512_atan_ps
#define _igen_mm512_mask_atan_ps        _igen_fb_mm512_mask_atan_ps
#define _igen_mm512_atanh_pd            _igen_fb_mm512_atanh_pd
#define _igen_mm512_mask_atanh_pd       _igen_fb_mm512_mask_atanh_pd
#define _igen_mm512_atanh_ps            _igen_fb_mm512_atanh_ps
#define _igen_mm512_mask_atanh_ps       _igen_fb_mm512_mask_atanh_ps
#define _igen_mm512_cbrt_pd             _igen_fb_mm512_cbrt_pd
#define _igen_mm512_mask_cbrt_pd        _igen_fb_mm512_mask_cbrt_pd
#define _igen_mm512_cbrt_ps             _igen_fb_mm512_cbrt_ps
#define _igen_mm512_mask_cbrt_ps        _igen_fb_mm512_mask_cbrt_ps
#define _igen_mm512_cdfnorm_pd          _igen_fb_mm512_cdfnorm_pd
#define _igen_mm512_mask_cdfnorm_pd     _igen_fb_mm512_mask_cdfnorm_pd
#define _igen_mm512_cdfnorm_ps          _igen_fb_mm512_cdfnorm_ps
#define _igen_mm512_mask_cdfnorm_ps     _igen_fb_mm512_mask_cdfnorm_ps
#define _igen_mm512_cdfnorminv_pd       _igen_fb_mm512_cdfnorminv_pd
#define _igen_mm512_mask_cdfnorminv_pd  _igen_fb_mm512_mask_cdfnorminv_
#define _igen_mm512_cdfnorminv_ps       _igen_fb_mm512_cdfnorminv_ps
#define _igen_mm512_mask_cdfnorminv_ps  _igen_fb_mm512_mask_cdfnorminv_
#define _igen_mm512_ceil_pd             _igen_fb_mm512_ceil_pd
#define _igen_mm512_mask_ceil_pd        _igen_fb_mm512_mask_ceil_pd
#define _igen_mm512_ceil_ps             _igen_fb_mm512_ceil_ps
#define _igen_mm512_mask_ceil_ps        _igen_fb_mm512_mask_ceil_ps
#define _igen_mm512_cos_pd              _igen_fb_mm512_cos_pd
#define _igen_mm512_mask_cos_pd         _igen_fb_mm512_mask_cos_pd
#define _igen_mm512_cos_ps              _igen_fb_mm512_cos_ps
#define _igen_mm512_mask_cos_ps         _igen_fb_mm512_mask_cos_ps
#define _igen_mm512_cosd_pd             _igen_fb_mm512_cosd_pd
#define _igen_mm512_mask_cosd_pd        _igen_fb_mm512_mask_cosd_pd
#define _igen_mm512_cosd_ps             _igen_fb_mm512_cosd_ps
#define _igen_mm512_mask_cosd_ps        _igen_fb_mm512_mask_cosd_ps
#define _igen_mm512_cosh_pd             _igen_fb_mm512_cosh_pd
#define _igen_mm512_mask_cosh_pd        _igen_fb_mm512_mask_cosh_pd
#define _igen_mm512_cosh_ps             _igen_fb_mm512_cosh_ps
#define _igen_mm512_mask_cosh_ps        _igen_fb_mm512_mask_cosh_ps
#define _igen_mm512_erf_pd              _igen_fb_mm512_erf_pd
#define _igen_mm512_mask_erf_pd         _igen_fb_mm512_mask_erf_pd
#define _igen_mm512_erfc_pd             _igen_fb_mm512_erfc_pd
#define _igen_mm512_mask_erfc_pd        _igen_fb_mm512_mask_erfc_pd
#define _igen_mm512_erf_ps              _igen_fb_mm512_erf_ps
#define _igen_mm512_mask_erf_ps         _igen_fb_mm512_mask_erf_ps
#define _igen_mm512_erfc_ps             _igen_fb_mm512_erfc_ps
#define _igen_mm512_mask_erfc_ps        _igen_fb_mm512_mask_erfc_ps
#define _igen_mm512_erfinv_pd           _igen_fb_mm512_erfinv_pd
#define _igen_mm512_mask_erfinv_pd      _igen_fb_mm512_mask_erfinv_pd
#define _igen_mm512_erfinv_ps           _igen_fb_mm512_erfinv_ps
#define _igen_mm512_mask_erfinv_ps      _igen_fb_mm512_mask_erfinv_ps
#define _igen_mm512_erfcinv_pd          _igen_fb_mm512_erfcinv_pd
#define _igen_mm512_mask_erfcinv_pd     _igen_fb_mm512_mask_erfcinv_pd
#define _igen_mm512_erfcinv_ps          _igen_fb_mm512_erfcinv_ps
#define _igen_mm512_mask_erfcinv_ps     _igen_fb_mm512_mask_erfcinv_ps
#define _igen_mm512_exp10_pd            _igen_fb_mm512_exp10_pd
#define _igen_mm512_mask_exp10_pd       _igen_fb_mm512_mask_exp10_pd
#define _igen_mm512_exp10_ps            _igen_fb_mm512_exp10_ps
#define _igen_mm512_mask_exp10_ps       _igen_fb_mm512_mask_exp10_ps
#define _igen_mm512_exp2_pd             _igen_fb_mm512_exp2_pd
#define _igen_mm512_mask_exp2_pd        _igen_fb_mm512_mask_exp2_pd
#define _igen_mm512_exp2_ps             _igen_fb_mm512_exp2_ps
#define _igen_mm512_mask_exp2_ps        _igen_fb_mm512_mask_exp2_ps
#define _igen_mm512_exp_pd              _igen_fb_mm512_exp_pd
#define _igen_mm512_mask_exp_pd         _igen_fb_mm512_mask_exp_pd
#define _igen_mm512_exp_ps              _igen_fb_mm512_exp_ps
#define _igen_mm512_mask_exp_ps         _igen_fb_mm512_mask_exp_ps
#define _igen_mm512_expm1_pd            _igen_fb_mm512_expm1_pd
#define _igen_mm512_mask_expm1_pd       _igen_fb_mm512_mask_expm1_pd
#define _igen_mm512_expm1_ps            _igen_fb_mm512_expm1_ps
#define _igen_mm512_mask_expm1_ps       _igen_fb_mm512_mask_expm1_ps
#define _igen_mm512_floor_pd            _igen_fb_mm512_floor_pd
#define _igen_mm512_mask_floor_pd       _igen_fb_mm512_mask_floor_pd
#define _igen_mm512_floor_ps            _igen_fb_mm512_floor_ps
#define _igen_mm512_mask_floor_ps       _igen_fb_mm512_mask_floor_ps
#define _igen_mm512_hypot_pd            _igen_fb_mm512_hypot_pd
#define _igen_mm512_mask_hypot_pd       _igen_fb_mm512_mask_hypot_pd
#define _igen_mm512_hypot_ps            _igen_fb_mm512_hypot_ps
#define _igen_mm512_mask_hypot_ps       _igen_fb_mm512_mask_hypot_ps
#define _igen_mm512_invsqrt_pd          _igen_fb_mm512_invsqrt_pd
#define _igen_mm512_mask_invsqrt_pd     _igen_fb_mm512_mask_invsqrt_pd
#define _igen_mm512_invsqrt_ps          _igen_fb_mm512_invsqrt_ps
#define _igen_mm512_mask_invsqrt_ps     _igen_fb_mm512_mask_invsqrt_ps
#define _igen_mm512_log10_pd            _igen_fb_mm512_log10_pd
#define _igen_mm512_mask_log10_pd       _igen_fb_mm512_mask_log10_pd
#define _igen_mm512_log10_ps            _igen_fb_mm512_log10_ps
#define _igen_mm512_mask_log10_ps       _igen_fb_mm512_mask_log10_ps
#define _igen_mm512_log1p_pd            _igen_fb_mm512_log1p_pd
#define _igen_mm512_mask_log1p_pd       _igen_fb_mm512_mask_log1p_pd
#define _igen_mm512_log1p_ps            _igen_fb_mm512_log1p_ps
#define _igen_mm512_mask_log1p_ps       _igen_fb_mm512_mask_log1p_ps
#define _igen_mm512_log2_pd             _igen_fb_mm512_log2_pd
#define _igen_mm512_mask_log2_pd        _igen_fb_mm512_mask_log2_pd
#define _igen_mm512_log_pd              _igen_fb_mm512_log_pd
#define _igen_mm512_mask_log_pd         _igen_fb_mm512_mask_log_pd
#define _igen_mm512_log_ps              _igen_fb_mm512_log_ps
#define _igen_mm512_mask_log_ps         _igen_fb_mm512_mask_log_ps
#define _igen_mm512_logb_pd             _igen_fb_mm512_logb_pd
#define _igen_mm512_mask_logb_pd        _igen_fb_mm512_mask_logb_pd
#define _igen_mm512_logb_ps             _igen_fb_mm512_logb_ps
#define _igen_mm512_mask_logb_ps        _igen_fb_mm512_mask_logb_ps
#define _igen_mm512_nearbyint_pd        _igen_fb_mm512_nearbyint_pd
#define _igen_mm512_mask_nearbyint_pd   _igen_fb_mm512_mask_nearbyint_p
#define _igen_mm512_nearbyint_ps        _igen_fb_mm512_nearbyint_ps
#define _igen_mm512_mask_nearbyint_ps   _igen_fb_mm512_mask_nearbyint_p
#define _igen_mm512_pow_pd              _igen_fb_mm512_pow_pd
#define _igen_mm512_mask_pow_pd         _igen_fb_mm512_mask_pow_pd
#define _igen_mm512_pow_ps              _igen_fb_mm512_pow_ps
#define _igen_mm512_mask_pow_ps         _igen_fb_mm512_mask_pow_ps
#define _igen_mm512_recip_pd            _igen_fb_mm512_recip_pd
#define _igen_mm512_mask_recip_pd       _igen_fb_mm512_mask_recip_pd
#define _igen_mm512_recip_ps            _igen_fb_mm512_recip_ps
#define _igen_mm512_mask_recip_ps       _igen_fb_mm512_mask_recip_ps
#define _igen_mm512_rint_pd             _igen_fb_mm512_rint_pd
#define _igen_mm512_mask_rint_pd        _igen_fb_mm512_mask_rint_pd
#define _igen_mm512_rint_ps             _igen_fb_mm512_rint_ps
#define _igen_mm512_mask_rint_ps        _igen_fb_mm512_mask_rint_ps
#define _igen_mm512_svml_round_pd       _igen_fb_mm512_svml_round_pd
#define _igen_mm512_mask_svml_round_pd  _igen_fb_mm512_mask_svml_round_
#define _igen_mm512_sin_pd              _igen_fb_mm512_sin_pd
#define _igen_mm512_mask_sin_pd         _igen_fb_mm512_mask_sin_pd
#define _igen_mm512_sin_ps              _igen_fb_mm512_sin_ps
#define _igen_mm512_mask_sin_ps         _igen_fb_mm512_mask_sin_ps
#define _igen_mm512_sinh_pd             _igen_fb_mm512_sinh_pd
#define _igen_mm512_mask_sinh_pd        _igen_fb_mm512_mask_sinh_pd
#define _igen_mm512_sinh_ps             _igen_fb_mm512_sinh_ps
#define _igen_mm512_mask_sinh_ps        _igen_fb_mm512_mask_sinh_ps
#define _igen_mm512_sind_pd             _igen_fb_mm512_sind_pd
#define _igen_mm512_mask_sind_pd        _igen_fb_mm512_mask_sind_pd
#define _igen_mm512_sind_ps             _igen_fb_mm512_sind_ps
#define _igen_mm512_mask_sind_ps        _igen_fb_mm512_mask_sind_ps
#define _igen_mm512_tan_pd              _igen_fb_mm512_tan_pd
#define _igen_mm512_mask_tan_pd         _igen_fb_mm512_mask_tan_pd
#define _igen_mm512_tan_ps              _igen_fb_mm512_tan_ps
#define _igen_mm512_mask_tan_ps         _igen_fb_mm512_mask_tan_ps
#define _igen_mm512_tand_pd             _igen_fb_mm512_tand_pd
#define _igen_mm512_mask_tand_pd        _igen_fb_mm512_mask_tand_pd
#define _igen_mm512_tand_ps             _igen_fb_mm512_tand_ps
#define _igen_mm512_mask_tand_ps        _igen_fb_mm512_mask_tand_ps
#define _igen_mm512_tanh_pd             _igen_fb_mm512_tanh_pd
#define _igen_mm512_mask_tanh_pd        _igen_fb_mm512_mask_tanh_pd
#define _igen_mm512_tanh_ps             _igen_fb_mm512_tanh_ps
#define _igen_mm512_mask_tanh_ps        _igen_fb_mm512_mask_tanh_ps
#define _igen_mm512_trunc_pd            _igen_fb_mm512_trunc_pd
#define _igen_mm512_mask_trunc_pd       _igen_fb_mm512_mask_trunc_pd
#define _igen_mm512_trunc_ps            _igen_fb_mm512_trunc_ps
#define _igen_mm512_mask_trunc_ps       _igen_fb_mm512_mask_trunc_ps
#define _igen_mm512_sincos_pd           _igen_fb_mm512_sincos_pd
#define _igen_mm512_mask_sincos_pd      _igen_fb_mm512_mask_sincos_pd
#define _igen_mm512_sincos_ps           _igen_fb_mm512_sincos_ps
#define _igen_mm512_mask_sincos_ps      _igen_fb_mm512_mask_sincos_ps

///
/// Optimized intrinsics
///
#ifdef IGEN_LIB_VECTORIZED
#include "igen_immintrin_opt.h"
#undef  _igen_mm256_add_pd
#define _igen_mm256_add_pd              _igen_op_mm256_add_pd
#undef  _igen_mm256_mul_pd
#define _igen_mm256_mul_pd              _igen_op_mm256_mul_pd
#undef  _igen_mm256_sub_pd
#define _igen_mm256_sub_pd              _igen_op_mm256_sub_pd
#undef  _igen_mm_load_sd
#define _igen_mm_load_sd                _igen_op_mm_load_sd
#undef  _igen_mm256_fmadd_pd
#define _igen_mm256_fmadd_pd            _igen_op_mm256_fmadd_pd
#undef  _igen_mm256_permute2f128_pd
#define _igen_mm256_permute2f128_pd     _igen_op_mm256_permute2f128_pd
#undef  _igen_mm256_shuffle_pd
#define _igen_mm256_shuffle_pd          _igen_op_mm256_shuffle_pd
#undef  _igen_mm256_loadu_pd
#define _igen_mm256_loadu_pd            _igen_op_mm256_loadu_pd
#undef  _igen_mm256_load_pd
#define _igen_mm256_load_pd             _igen_op_mm256_load_pd
#undef  _igen_mm256_storeu_pd
#define _igen_mm256_storeu_pd           _igen_op_mm256_storeu_pd
#undef  _igen_mm256_unpackhi_pd
#define _igen_mm256_unpackhi_pd         _igen_op_mm256_unpackhi_pd
#undef  _igen_mm256_unpacklo_pd
#define _igen_mm256_unpacklo_pd         _igen_op_mm256_unpacklo_pd
#undef  _igen_mm256_set_pd
#define _igen_mm256_set_pd              _igen_op_mm256_set_pd
#undef  _igen_mm256_castpd256_pd128
#define _igen_mm256_castpd256_pd128     _igen_op_mm256_castpd256_pd128
#undef  _igen_mm256_broadcast_sd
#define _igen_mm256_broadcast_sd        _igen_op_mm256_broadcast_sd
#undef  _igen_mm256_broadcastsd_pd
#define _igen_mm256_broadcastsd_pd      _igen_op_mm256_broadcastsd_pd
#undef  _igen_mm256_set1_pd
#define _igen_mm256_set1_pd             _igen_op_mm256_set1_pd
#undef  _igen_mm256_extractf128_pd
#define _igen_mm256_extractf128_pd      _igen_op_mm256_extractf128_pd
#undef  _igen_mm_add_pd
#define _igen_mm_add_pd                 _igen_op_mm_add_pd
#undef  _igen_mm_unpackhi_pd
#define _igen_mm_unpackhi_pd            _igen_op_mm_unpackhi_pd
#undef  _igen_mm_cvtsd_f64
#define _igen_mm_cvtsd_f64              _igen_op_mm_cvtsd_f64
#endif