#pragma once

///
/// All types are promoted to double-double
///

#include "igen_dd_immintrin_types.h"

#ifdef __cplusplus
extern "C" {
#endif

ddi_4 _igen_dd_fb_mm_cvtsi32_ss(ddi_4 _a, int b);
ddi_4 _igen_dd_fb_mm_cvtsi64_ss(ddi_4 _a, long b);
ddi_4 _igen_dd_fb_mm_cvtpi32_ps(ddi_4 _a, __m64 _b);
ddi_4 _igen_dd_fb_mm_cvtpi16_ps(__m64 _a);
ddi_4 _igen_dd_fb_mm_cvtpu16_ps(__m64 _a);
ddi_4 _igen_dd_fb_mm_cvtpi8_ps(__m64 _a);
ddi_4 _igen_dd_fb_mm_cvtpu8_ps(__m64 _a);
ddi_4 _igen_dd_fb_mm_cvtpi32x2_ps(__m64 _a, __m64 _b);
ddi_4 _igen_dd_fb_mm_add_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_add_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_sub_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_sub_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_mul_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_mul_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_div_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_div_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_sqrt_ss(ddi_4 _a);
ddi_4 _igen_dd_fb_mm_sqrt_ps(ddi_4 _a);
ddi_4 _igen_dd_fb_mm_rcp_ss(ddi_4 _a);
ddi_4 _igen_dd_fb_mm_rcp_ps(ddi_4 _a);
ddi_4 _igen_dd_fb_mm_rsqrt_ss(ddi_4 _a);
ddi_4 _igen_dd_fb_mm_rsqrt_ps(ddi_4 _a);
ddi_4 _igen_dd_fb_mm_min_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_min_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_max_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_max_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_and_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_andnot_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_or_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_xor_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpeq_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpeq_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmplt_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmplt_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmple_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmple_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpgt_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpgt_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpge_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpge_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpneq_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpneq_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpnlt_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpnlt_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpnle_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpnle_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpngt_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpngt_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpnge_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpnge_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpord_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpord_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpunord_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_cmpunord_ps(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_comieq_ss(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_comilt_ss(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_comile_ss(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_comigt_ss(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_comige_ss(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_comineq_ss(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_ucomieq_ss(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_ucomilt_ss(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_ucomile_ss(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_ucomigt_ss(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_ucomige_ss(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_ucomineq_ss(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_cvtss_si32(ddi_4 _a);
int _igen_dd_fb_mm_cvt_ss2si(ddi_4 _a);
long _igen_dd_fb_mm_cvtss_si64(ddi_4 _a);
dd_I _igen_dd_fb_mm_cvtss_f32(ddi_4 _a);
__m64 _igen_dd_fb_mm_cvtps_pi32(ddi_4 _a);
__m64 _igen_dd_fb_mm_cvt_ps2pi(ddi_4 _a);
int _igen_dd_fb_mm_cvttss_si32(ddi_4 _a);
int _igen_dd_fb_mm_cvtt_ss2si(ddi_4 _a);
long _igen_dd_fb_mm_cvttss_si64(ddi_4 _a);
__m64 _igen_dd_fb_mm_cvttps_pi32(ddi_4 _a);
__m64 _igen_dd_fb_mm_cvtt_ps2pi(ddi_4 _a);
__m64 _igen_dd_fb_mm_cvtps_pi16(ddi_4 _a);
__m64 _igen_dd_fb_mm_cvtps_pi8(ddi_4 _a);
ddi_4 _igen_dd_fb_mm_set_ss(dd_I a);
ddi_4 _igen_dd_fb_mm_set1_ps(dd_I a);
ddi_4 _igen_dd_fb_mm_set_ps1(dd_I a);
ddi_4 _igen_dd_fb_mm_set_ps(dd_I e3, dd_I e2, dd_I e1, dd_I e0);
ddi_4 _igen_dd_fb_mm_setr_ps(dd_I e3, dd_I e2, dd_I e1, dd_I e0);
ddi_4 _igen_dd_fb_mm_setzero_ps();
ddi_4 _igen_dd_fb_mm_load_ss(const dd_I *mem_addr);
ddi_4 _igen_dd_fb_mm_load1_ps(const dd_I *mem_addr);
ddi_4 _igen_dd_fb_mm_load_ps1(const dd_I *mem_addr);
ddi_4 _igen_dd_fb_mm_load_ps(const dd_I *mem_addr);
ddi_4 _igen_dd_fb_mm_loadu_ps(const dd_I *mem_addr);
ddi_4 _igen_dd_fb_mm_loadr_ps(const dd_I *mem_addr);
void _igen_dd_fb_mm_stream_ps(dd_I *mem_addr, ddi_4 _a);
void _igen_dd_fb_mm_store_ss(dd_I *mem_addr, ddi_4 _a);
void _igen_dd_fb_mm_store1_ps(dd_I *mem_addr, ddi_4 _a);
void _igen_dd_fb_mm_store_ps1(dd_I *mem_addr, ddi_4 _a);
void _igen_dd_fb_mm_store_ps(dd_I *mem_addr, ddi_4 _a);
void _igen_dd_fb_mm_storeu_ps(dd_I *mem_addr, ddi_4 _a);
void _igen_dd_fb_mm_storer_ps(dd_I *mem_addr, ddi_4 _a);
ddi_4 _igen_dd_fb_mm_move_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_shuffle_ps(ddi_4 _a, ddi_4 _b, unsigned int imm8);
ddi_4 _igen_dd_fb_mm_unpackhi_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_unpacklo_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_movehl_ps(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_movelh_ps(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_movemask_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_cvtepi32_pd(__m128i _a);
ddi_2 _igen_dd_fb_mm_cvtsi32_sd(ddi_2 _a, int b);
ddi_2 _igen_dd_fb_mm_cvtsi64_sd(ddi_2 _a, long b);
ddi_2 _igen_dd_fb_mm_cvtsi64x_sd(ddi_2 _a, long b);
ddi_4 _igen_dd_fb_mm_cvtepi32_ps(__m128i _a);
ddi_2 _igen_dd_fb_mm_cvtpi32_pd(__m64 _a);
ddi_2 _igen_dd_fb_mm_add_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_add_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_div_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_div_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_max_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_max_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_min_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_min_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_mul_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_mul_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_sqrt_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_sqrt_pd(ddi_2 _a);
ddi_2 _igen_dd_fb_mm_sub_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_sub_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_and_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_andnot_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_or_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_xor_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpeq_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmplt_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmple_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpgt_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpge_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpord_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpunord_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpneq_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpnlt_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpnle_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpngt_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpnge_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpeq_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmplt_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmple_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpgt_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpge_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpord_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpunord_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpneq_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpnlt_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpnle_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpngt_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_cmpnge_pd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_comieq_sd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_comilt_sd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_comile_sd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_comigt_sd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_comige_sd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_comineq_sd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_ucomieq_sd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_ucomilt_sd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_ucomile_sd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_ucomigt_sd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_ucomige_sd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_ucomineq_sd(ddi_2 _a, ddi_2 _b);
ddi_4 _igen_dd_fb_mm_cvtpd_ps(ddi_2 _a);
ddi_2 _igen_dd_fb_mm_cvtps_pd(ddi_4 _a);
__m128i _igen_dd_fb_mm_cvtpd_epi32(ddi_2 _a);
int _igen_dd_fb_mm_cvtsd_si32(ddi_2 _a);
long _igen_dd_fb_mm_cvtsd_si64(ddi_2 _a);
long _igen_dd_fb_mm_cvtsd_si64x(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_cvtsd_ss(ddi_4 _a, ddi_2 _b);
dd_I _igen_dd_fb_mm_cvtsd_f64(ddi_2 _a);
ddi_2 _igen_dd_fb_mm_cvtss_sd(ddi_2 _a, ddi_4 _b);
__m128i _igen_dd_fb_mm_cvttpd_epi32(ddi_2 _a);
int _igen_dd_fb_mm_cvttsd_si32(ddi_2 _a);
long _igen_dd_fb_mm_cvttsd_si64(ddi_2 _a);
long _igen_dd_fb_mm_cvttsd_si64x(ddi_2 _a);
__m128i _igen_dd_fb_mm_cvtps_epi32(ddi_4 _a);
__m128i _igen_dd_fb_mm_cvttps_epi32(ddi_4 _a);
__m64 _igen_dd_fb_mm_cvtpd_pi32(ddi_2 _a);
__m64 _igen_dd_fb_mm_cvttpd_pi32(ddi_2 _a);
ddi_2 _igen_dd_fb_mm_set_sd(dd_I a);
ddi_2 _igen_dd_fb_mm_set1_pd(dd_I a);
ddi_2 _igen_dd_fb_mm_set_pd1(dd_I a);
ddi_2 _igen_dd_fb_mm_set_pd(dd_I e1, dd_I e0);
ddi_2 _igen_dd_fb_mm_setr_pd(dd_I e1, dd_I e0);
ddi_2 _igen_dd_fb_mm_setzero_pd();
ddi_2 _igen_dd_fb_mm_load_pd(const dd_I *mem_addr);
ddi_2 _igen_dd_fb_mm_load1_pd(const dd_I *mem_addr);
ddi_2 _igen_dd_fb_mm_load_pd1(const dd_I *mem_addr);
ddi_2 _igen_dd_fb_mm_loadr_pd(const dd_I *mem_addr);
ddi_2 _igen_dd_fb_mm_loadu_pd(const dd_I *mem_addr);
ddi_2 _igen_dd_fb_mm_load_sd(const dd_I *mem_addr);
ddi_2 _igen_dd_fb_mm_loadh_pd(ddi_2 _a, const dd_I *mem_addr);
ddi_2 _igen_dd_fb_mm_loadl_pd(ddi_2 _a, const dd_I *mem_addr);
void _igen_dd_fb_mm_stream_pd(dd_I *mem_addr, ddi_2 _a);
void _igen_dd_fb_mm_store_sd(dd_I *mem_addr, ddi_2 _a);
void _igen_dd_fb_mm_store1_pd(dd_I *mem_addr, ddi_2 _a);
void _igen_dd_fb_mm_store_pd1(dd_I *mem_addr, ddi_2 _a);
void _igen_dd_fb_mm_store_pd(dd_I *mem_addr, ddi_2 _a);
void _igen_dd_fb_mm_storeu_pd(dd_I *mem_addr, ddi_2 _a);
void _igen_dd_fb_mm_storer_pd(dd_I *mem_addr, ddi_2 _a);
void _igen_dd_fb_mm_storeh_pd(dd_I *mem_addr, ddi_2 _a);
void _igen_dd_fb_mm_storel_pd(dd_I *mem_addr, ddi_2 _a);
ddi_2 _igen_dd_fb_mm_unpackhi_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_unpacklo_pd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_movemask_pd(ddi_2 _a);
ddi_2 _igen_dd_fb_mm_shuffle_pd(ddi_2 _a, ddi_2 _b, int imm8);
ddi_2 _igen_dd_fb_mm_move_sd(ddi_2 _a, ddi_2 _b);
ddi_4 _igen_dd_fb_mm_castpd_ps(ddi_2 _a);
__m128i _igen_dd_fb_mm_castpd_si128(ddi_2 _a);
ddi_2 _igen_dd_fb_mm_castps_pd(ddi_4 _a);
__m128i _igen_dd_fb_mm_castps_si128(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_castsi128_pd(__m128i _a);
ddi_4 _igen_dd_fb_mm_castsi128_ps(__m128i _a);
dd_I _igen_dd_fb_cvtsh_ss(__mmask16 a);
__mmask16 _igen_dd_fb_cvtss_sh(dd_I a, int rounding);
ddi_4 _igen_dd_fb_mm_cvtph_ps(__m128i _a);
__m128i _igen_dd_fb_mm_cvtps_ph(ddi_4 _a, int rounding);
ddi_4 _igen_dd_fb_mm_addsub_ps(ddi_4 _a, ddi_4 _b);
ddi_2 _igen_dd_fb_mm_addsub_pd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_hadd_pd(ddi_2 _a, ddi_2 _b);
ddi_4 _igen_dd_fb_mm_hadd_ps(ddi_4 _a, ddi_4 _b);
ddi_2 _igen_dd_fb_mm_hsub_pd(ddi_2 _a, ddi_2 _b);
ddi_4 _igen_dd_fb_mm_hsub_ps(ddi_4 _a, ddi_4 _b);
ddi_2 _igen_dd_fb_mm_movedup_pd(ddi_2 _a);
ddi_2 _igen_dd_fb_mm_loaddup_pd(const dd_I *mem_addr);
ddi_4 _igen_dd_fb_mm_movehdup_ps(ddi_4 _a);
ddi_4 _igen_dd_fb_mm_moveldup_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_blend_pd(ddi_2 _a, ddi_2 _b, int imm8);
ddi_4 _igen_dd_fb_mm_blend_ps(ddi_4 _a, ddi_4 _b, int imm8);
ddi_2 _igen_dd_fb_mm_blendv_pd(ddi_2 _a, ddi_2 _b, ddi_2 _mask);
ddi_4 _igen_dd_fb_mm_blendv_ps(ddi_4 _a, ddi_4 _b, ddi_4 _mask);
ddi_2 _igen_dd_fb_mm_dp_pd(ddi_2 _a, ddi_2 _b, int imm8);
ddi_4 _igen_dd_fb_mm_dp_ps(ddi_4 _a, ddi_4 _b, int imm8);
int _igen_dd_fb_mm_extract_ps(ddi_4 _a, int imm8);
ddi_4 _igen_dd_fb_mm_insert_ps(ddi_4 _a, ddi_4 _b, int imm8);
ddi_2 _igen_dd_fb_mm_round_pd(ddi_2 _a, int rounding);
ddi_2 _igen_dd_fb_mm_floor_pd(ddi_2 _a);
ddi_2 _igen_dd_fb_mm_ceil_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_round_ps(ddi_4 _a, int rounding);
ddi_4 _igen_dd_fb_mm_floor_ps(ddi_4 _a);
ddi_4 _igen_dd_fb_mm_ceil_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_round_sd(ddi_2 _a, ddi_2 _b, int rounding);
ddi_2 _igen_dd_fb_mm_floor_sd(ddi_2 _a, ddi_2 _b);
ddi_2 _igen_dd_fb_mm_ceil_sd(ddi_2 _a, ddi_2 _b);
ddi_4 _igen_dd_fb_mm_round_ss(ddi_4 _a, ddi_4 _b, int rounding);
ddi_4 _igen_dd_fb_mm_floor_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm_ceil_ss(ddi_4 _a, ddi_4 _b);
ddi_4 _igen_dd_fb_mm256_add_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_add_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_addsub_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_addsub_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_and_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_and_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_andnot_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_andnot_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_blend_pd(ddi_4 _a, ddi_4 _b, int imm8);
ddi_8 _igen_dd_fb_mm256_blend_ps(ddi_8 _a, ddi_8 _b, int imm8);
ddi_4 _igen_dd_fb_mm256_blendv_pd(ddi_4 _a, ddi_4 _b, ddi_4 _mask);
ddi_8 _igen_dd_fb_mm256_blendv_ps(ddi_8 _a, ddi_8 _b, ddi_8 _mask);
ddi_4 _igen_dd_fb_mm256_div_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_div_ps(ddi_8 _a, ddi_8 _b);
ddi_8 _igen_dd_fb_mm256_dp_ps(ddi_8 _a, ddi_8 _b, int imm8);
ddi_4 _igen_dd_fb_mm256_hadd_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_hadd_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_hsub_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_hsub_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_max_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_max_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_min_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_min_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_mul_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_mul_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_or_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_or_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_shuffle_pd(ddi_4 _a, ddi_4 _b, int imm8);
ddi_8 _igen_dd_fb_mm256_shuffle_ps(ddi_8 _a, ddi_8 _b, int imm8);
ddi_4 _igen_dd_fb_mm256_sub_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_sub_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_xor_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_xor_ps(ddi_8 _a, ddi_8 _b);
ddi_2 _igen_dd_fb_mm_cmp_pd(ddi_2 _a, ddi_2 _b, int imm8);
ddi_4 _igen_dd_fb_mm256_cmp_pd(ddi_4 _a, ddi_4 _b, int imm8);
ddi_4 _igen_dd_fb_mm_cmp_ps(ddi_4 _a, ddi_4 _b, int imm8);
ddi_8 _igen_dd_fb_mm256_cmp_ps(ddi_8 _a, ddi_8 _b, int imm8);
ddi_2 _igen_dd_fb_mm_cmp_sd(ddi_2 _a, ddi_2 _b, int imm8);
ddi_4 _igen_dd_fb_mm_cmp_ss(ddi_4 _a, ddi_4 _b, int imm8);
ddi_4 _igen_dd_fb_mm256_cvtepi32_pd(__m128i _a);
ddi_8 _igen_dd_fb_mm256_cvtepi32_ps(__m256i _a);
ddi_4 _igen_dd_fb_mm256_cvtpd_ps(ddi_4 _a);
__m256i _igen_dd_fb_mm256_cvtps_epi32(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_cvtps_pd(ddi_4 _a);
__m128i _igen_dd_fb_mm256_cvttpd_epi32(ddi_4 _a);
__m128i _igen_dd_fb_mm256_cvtpd_epi32(ddi_4 _a);
__m256i _igen_dd_fb_mm256_cvttps_epi32(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_extractf128_ps(ddi_8 _a, int imm8);
ddi_2 _igen_dd_fb_mm256_extractf128_pd(ddi_4 _a, int imm8);
ddi_8 _igen_dd_fb_mm256_permutevar_ps(ddi_8 _a, __m256i _b);
ddi_4 _igen_dd_fb_mm_permutevar_ps(ddi_4 _a, __m128i _b);
ddi_8 _igen_dd_fb_mm256_permute_ps(ddi_8 _a, int imm8);
ddi_4 _igen_dd_fb_mm_permute_ps(ddi_4 _a, int imm8);
ddi_4 _igen_dd_fb_mm256_permutevar_pd(ddi_4 _a, __m256i _b);
ddi_2 _igen_dd_fb_mm_permutevar_pd(ddi_2 _a, __m128i _b);
ddi_4 _igen_dd_fb_mm256_permute_pd(ddi_4 _a, int imm8);
ddi_2 _igen_dd_fb_mm_permute_pd(ddi_2 _a, int imm8);
ddi_8 _igen_dd_fb_mm256_permute2f128_ps(ddi_8 _a, ddi_8 _b, int imm8);
ddi_4 _igen_dd_fb_mm256_permute2f128_pd(ddi_4 _a, ddi_4 _b, int imm8);
ddi_8 _igen_dd_fb_mm256_broadcast_ss(const dd_I *mem_addr);
ddi_4 _igen_dd_fb_mm_broadcast_ss(const dd_I *mem_addr);
ddi_4 _igen_dd_fb_mm256_broadcast_sd(const dd_I *mem_addr);
ddi_8 _igen_dd_fb_mm256_broadcast_ps(ddi_4 *_mem_addr);
ddi_4 _igen_dd_fb_mm256_broadcast_pd(ddi_2 *_mem_addr);
ddi_8 _igen_dd_fb_mm256_insertf128_ps(ddi_8 _a, ddi_4 _b, int imm8);
ddi_4 _igen_dd_fb_mm256_insertf128_pd(ddi_4 _a, ddi_2 _b, int imm8);
ddi_4 _igen_dd_fb_mm256_load_pd(const dd_I *mem_addr);
void _igen_dd_fb_mm256_store_pd(dd_I *mem_addr, ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_load_ps(const dd_I *mem_addr);
void _igen_dd_fb_mm256_store_ps(dd_I *mem_addr, ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_loadu_pd(const dd_I *mem_addr);
void _igen_dd_fb_mm256_storeu_pd(dd_I *mem_addr, ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_loadu_ps(const dd_I *mem_addr);
void _igen_dd_fb_mm256_storeu_ps(dd_I *mem_addr, ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_maskload_pd(const dd_I *mem_addr, __m256i _mask);
void _igen_dd_fb_mm256_maskstore_pd(dd_I *mem_addr, __m256i _mask, ddi_4 _a);
ddi_2 _igen_dd_fb_mm_maskload_pd(const dd_I *mem_addr, __m128i _mask);
void _igen_dd_fb_mm_maskstore_pd(dd_I *mem_addr, __m128i _mask, ddi_2 _a);
ddi_8 _igen_dd_fb_mm256_maskload_ps(const dd_I *mem_addr, __m256i _mask);
void _igen_dd_fb_mm256_maskstore_ps(dd_I *mem_addr, __m256i _mask, ddi_8 _a);
ddi_4 _igen_dd_fb_mm_maskload_ps(const dd_I *mem_addr, __m128i _mask);
void _igen_dd_fb_mm_maskstore_ps(dd_I *mem_addr, __m128i _mask, ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_movehdup_ps(ddi_8 _a);
ddi_8 _igen_dd_fb_mm256_moveldup_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_movedup_pd(ddi_4 _a);
void _igen_dd_fb_mm256_stream_pd(dd_I *mem_addr, ddi_4 _a);
void _igen_dd_fb_mm256_stream_ps(dd_I *mem_addr, ddi_8 _a);
ddi_8 _igen_dd_fb_mm256_rcp_ps(ddi_8 _a);
ddi_8 _igen_dd_fb_mm256_rsqrt_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_sqrt_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_sqrt_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_round_pd(ddi_4 _a, int rounding);
ddi_8 _igen_dd_fb_mm256_round_ps(ddi_8 _a, int rounding);
ddi_4 _igen_dd_fb_mm256_unpackhi_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_unpackhi_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_unpacklo_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_unpacklo_ps(ddi_8 _a, ddi_8 _b);
int _igen_dd_fb_mm256_testz_pd(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm256_testc_pd(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm256_testnzc_pd(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_testz_pd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_testc_pd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm_testnzc_pd(ddi_2 _a, ddi_2 _b);
int _igen_dd_fb_mm256_testz_ps(ddi_8 _a, ddi_8 _b);
int _igen_dd_fb_mm256_testc_ps(ddi_8 _a, ddi_8 _b);
int _igen_dd_fb_mm256_testnzc_ps(ddi_8 _a, ddi_8 _b);
int _igen_dd_fb_mm_testz_ps(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_testc_ps(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm_testnzc_ps(ddi_4 _a, ddi_4 _b);
int _igen_dd_fb_mm256_movemask_pd(ddi_4 _a);
int _igen_dd_fb_mm256_movemask_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_setzero_pd();
ddi_8 _igen_dd_fb_mm256_setzero_ps();
ddi_4 _igen_dd_fb_mm256_set_pd(dd_I e3, dd_I e2, dd_I e1, dd_I e0);
ddi_8 _igen_dd_fb_mm256_set_ps(dd_I e7, dd_I e6, dd_I e5, dd_I e4,
                             dd_I e3, dd_I e2, dd_I e1, dd_I e0);
ddi_4 _igen_dd_fb_mm256_setr_pd(dd_I e3, dd_I e2, dd_I e1, dd_I e0);
ddi_8 _igen_dd_fb_mm256_setr_ps(dd_I e7, dd_I e6, dd_I e5, dd_I e4,
                              dd_I e3, dd_I e2, dd_I e1, dd_I e0);
ddi_4 _igen_dd_fb_mm256_set1_pd(dd_I a);
ddi_8 _igen_dd_fb_mm256_set1_ps(dd_I a);
ddi_8 _igen_dd_fb_mm256_castpd_ps(ddi_4 _a);
ddi_4 _igen_dd_fb_mm256_castps_pd(ddi_8 _a);
__m256i _igen_dd_fb_mm256_castps_si256(ddi_8 _a);
__m256i _igen_dd_fb_mm256_castpd_si256(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_castsi256_ps(__m256i _a);
ddi_4 _igen_dd_fb_mm256_castsi256_pd(__m256i _a);
ddi_4 _igen_dd_fb_mm256_castps256_ps128(ddi_8 _a);
ddi_2 _igen_dd_fb_mm256_castpd256_pd128(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_castps128_ps256(ddi_4 _a);
ddi_4 _igen_dd_fb_mm256_castpd128_pd256(ddi_2 _a);
ddi_8 _igen_dd_fb_mm256_zextps128_ps256(ddi_4 _a);
ddi_4 _igen_dd_fb_mm256_zextpd128_pd256(ddi_2 _a);
ddi_8 _igen_dd_fb_mm256_floor_ps(ddi_8 _a);
ddi_8 _igen_dd_fb_mm256_ceil_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_floor_pd(ddi_4 _a);
ddi_4 _igen_dd_fb_mm256_ceil_pd(ddi_4 _a);
ddi_4 _igen_dd_fb_mm_undefined_ps();
ddi_2 _igen_dd_fb_mm_undefined_pd();
ddi_8 _igen_dd_fb_mm256_undefined_ps();
ddi_4 _igen_dd_fb_mm256_undefined_pd();
ddi_8 _igen_dd_fb_mm256_set_m128(ddi_4 _hi, ddi_4 _lo);
ddi_4 _igen_dd_fb_mm256_set_m128d(ddi_2 _hi, ddi_2 _lo);
ddi_8 _igen_dd_fb_mm256_setr_m128(ddi_4 _lo, ddi_4 _hi);
ddi_4 _igen_dd_fb_mm256_setr_m128d(ddi_2 _lo, ddi_2 _hi);
ddi_8 _igen_dd_fb_mm256_loadu2_m128(const dd_I *hiaddr, const dd_I *loaddr);
ddi_4 _igen_dd_fb_mm256_loadu2_m128d(const dd_I *hiaddr,
                                   const dd_I *loaddr);
void _igen_dd_fb_mm256_storeu2_m128(dd_I *hiaddr, dd_I *loaddr, ddi_8 _a);
void _igen_dd_fb_mm256_storeu2_m128d(dd_I *hiaddr, dd_I *loaddr, ddi_4 _a);
ddi_2 _igen_dd_fb_mm_broadcastsd_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm256_broadcastsd_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_broadcastss_ps(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_broadcastss_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_i32gather_pd(const dd_I *base_addr, __m128i _vindex,
                                int scale);
ddi_4 _igen_dd_fb_mm256_i32gather_pd(const dd_I *base_addr, __m128i _vindex,
                                   int scale);
ddi_4 _igen_dd_fb_mm_i32gather_ps(const dd_I *base_addr, __m128i _vindex,
                                int scale);
ddi_8 _igen_dd_fb_mm256_i32gather_ps(const dd_I *base_addr, __m256i _vindex,
                                   int scale);
ddi_2 _igen_dd_fb_mm_i64gather_pd(const dd_I *base_addr, __m128i _vindex,
                                int scale);
ddi_4 _igen_dd_fb_mm256_i64gather_pd(const dd_I *base_addr, __m256i _vindex,
                                   int scale);
ddi_4 _igen_dd_fb_mm_i64gather_ps(const dd_I *base_addr, __m128i _vindex,
                                int scale);
ddi_4 _igen_dd_fb_mm256_i64gather_ps(const dd_I *base_addr, __m256i _vindex,
                                   int scale);
ddi_2 _igen_dd_fb_mm_mask_i32gather_pd(ddi_2 _src, const dd_I *base_addr,
                                     __m128i _vindex, ddi_2 _mask, int scale);
ddi_4 _igen_dd_fb_mm256_mask_i32gather_pd(ddi_4 _src, const dd_I *base_addr,
                                        __m128i _vindex, ddi_4 _mask,
                                        int scale);
ddi_4 _igen_dd_fb_mm_mask_i32gather_ps(ddi_4 _src, const dd_I *base_addr,
                                     __m128i _vindex, ddi_4 _mask, int scale);
ddi_8 _igen_dd_fb_mm256_mask_i32gather_ps(ddi_8 _src, const dd_I *base_addr,
                                        __m256i _vindex, ddi_8 _mask,
                                        int scale);
ddi_2 _igen_dd_fb_mm_mask_i64gather_pd(ddi_2 _src, const dd_I *base_addr,
                                     __m128i _vindex, ddi_2 _mask, int scale);
ddi_4 _igen_dd_fb_mm256_mask_i64gather_pd(ddi_4 _src, const dd_I *base_addr,
                                        __m256i _vindex, ddi_4 _mask,
                                        int scale);
ddi_4 _igen_dd_fb_mm_mask_i64gather_ps(ddi_4 _src, const dd_I *base_addr,
                                     __m128i _vindex, ddi_4 _mask, int scale);
ddi_4 _igen_dd_fb_mm256_mask_i64gather_ps(ddi_4 _src, const dd_I *base_addr,
                                        __m256i _vindex, ddi_4 _mask,
                                        int scale);
ddi_4 _igen_dd_fb_mm256_permute4x64_pd(ddi_4 _a, int imm8);
ddi_8 _igen_dd_fb_mm256_permutevar8x32_ps(ddi_8 _a, __m256i _idx);
ddi_2 _igen_dd_fb_mm_fmadd_pd(ddi_2 _a, ddi_2 _b, ddi_2 _c);
ddi_4 _igen_dd_fb_mm256_fmadd_pd(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_4 _igen_dd_fb_mm_fmadd_ps(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_8 _igen_dd_fb_mm256_fmadd_ps(ddi_8 _a, ddi_8 _b, ddi_8 _c);
ddi_2 _igen_dd_fb_mm_fmadd_sd(ddi_2 _a, ddi_2 _b, ddi_2 _c);
ddi_4 _igen_dd_fb_mm_fmadd_ss(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_2 _igen_dd_fb_mm_fmaddsub_pd(ddi_2 _a, ddi_2 _b, ddi_2 _c);
ddi_4 _igen_dd_fb_mm256_fmaddsub_pd(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_4 _igen_dd_fb_mm_fmaddsub_ps(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_8 _igen_dd_fb_mm256_fmaddsub_ps(ddi_8 _a, ddi_8 _b, ddi_8 _c);
ddi_2 _igen_dd_fb_mm_fmsub_pd(ddi_2 _a, ddi_2 _b, ddi_2 _c);
ddi_4 _igen_dd_fb_mm256_fmsub_pd(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_4 _igen_dd_fb_mm_fmsub_ps(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_8 _igen_dd_fb_mm256_fmsub_ps(ddi_8 _a, ddi_8 _b, ddi_8 _c);
ddi_2 _igen_dd_fb_mm_fmsub_sd(ddi_2 _a, ddi_2 _b, ddi_2 _c);
ddi_4 _igen_dd_fb_mm_fmsub_ss(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_2 _igen_dd_fb_mm_fmsubadd_pd(ddi_2 _a, ddi_2 _b, ddi_2 _c);
ddi_4 _igen_dd_fb_mm256_fmsubadd_pd(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_4 _igen_dd_fb_mm_fmsubadd_ps(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_8 _igen_dd_fb_mm256_fmsubadd_ps(ddi_8 _a, ddi_8 _b, ddi_8 _c);
ddi_2 _igen_dd_fb_mm_fnmadd_pd(ddi_2 _a, ddi_2 _b, ddi_2 _c);
ddi_4 _igen_dd_fb_mm256_fnmadd_pd(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_4 _igen_dd_fb_mm_fnmadd_ps(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_8 _igen_dd_fb_mm256_fnmadd_ps(ddi_8 _a, ddi_8 _b, ddi_8 _c);
ddi_2 _igen_dd_fb_mm_fnmadd_sd(ddi_2 _a, ddi_2 _b, ddi_2 _c);
ddi_4 _igen_dd_fb_mm_fnmadd_ss(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_2 _igen_dd_fb_mm_fnmsub_pd(ddi_2 _a, ddi_2 _b, ddi_2 _c);
ddi_4 _igen_dd_fb_mm256_fnmsub_pd(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_4 _igen_dd_fb_mm_fnmsub_ps(ddi_4 _a, ddi_4 _b, ddi_4 _c);
ddi_8 _igen_dd_fb_mm256_fnmsub_ps(ddi_8 _a, ddi_8 _b, ddi_8 _c);
ddi_2 _igen_dd_fb_mm_fnmsub_sd(ddi_2 _a, ddi_2 _b, ddi_2 _c);
ddi_4 _igen_dd_fb_mm_fnmsub_ss(ddi_4 _a, ddi_4 _b, ddi_4 _c);
unsigned int _igen_dd_fb_castf32_u32(dd_I a);
long _igen_dd_fb_castf64_u64(dd_I a);
dd_I _igen_dd_fb_castu32_f32(unsigned int a);
dd_I _igen_dd_fb_castu64_f64(long a);
ddi_2 _igen_dd_fb_mm_acos_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_acos_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_acosh_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_acosh_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_asin_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_asin_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_asinh_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_asinh_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_atan_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_atan_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_atan2_pd(ddi_2 _a, ddi_2 _b);
ddi_4 _igen_dd_fb_mm_atan2_ps(ddi_4 _a, ddi_4 _b);
ddi_2 _igen_dd_fb_mm_atanh_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_atanh_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_cbrt_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_cbrt_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_cdfnorm_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_cdfnorm_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_cdfnorminv_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_cdfnorminv_ps(ddi_4 _a);
ddi_4 _igen_dd_fb_mm_cexp_ps(ddi_4 _a);
ddi_4 _igen_dd_fb_mm_clog_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_cos_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_cos_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_cosd_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_cosd_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_cosh_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_cosh_ps(ddi_4 _a);
ddi_4 _igen_dd_fb_mm_csqrt_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_erf_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_erf_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_erfc_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_erfc_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_erfcinv_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_erfcinv_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_erfinv_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_erfinv_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_exp_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_exp_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_exp10_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_exp10_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_exp2_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_exp2_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_expm1_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_expm1_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_hypot_pd(ddi_2 _a, ddi_2 _b);
ddi_4 _igen_dd_fb_mm_hypot_ps(ddi_4 _a, ddi_4 _b);
ddi_2 _igen_dd_fb_mm_invcbrt_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_invcbrt_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_invsqrt_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_invsqrt_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_log_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_log_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_log10_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_log10_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_log1p_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_log1p_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_log2_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_log2_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_logb_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_logb_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_pow_pd(ddi_2 _a, ddi_2 _b);
ddi_4 _igen_dd_fb_mm_pow_ps(ddi_4 _a, ddi_4 _b);
ddi_2 _igen_dd_fb_mm_sin_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_sin_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_sincos_pd(ddi_2 *_mem_addr, ddi_2 _a);
ddi_4 _igen_dd_fb_mm_sincos_ps(ddi_4 *_mem_addr, ddi_4 _a);
ddi_2 _igen_dd_fb_mm_sind_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_sind_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_sinh_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_sinh_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_svml_ceil_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_svml_ceil_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_svml_floor_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_svml_floor_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_svml_round_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_svml_round_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_svml_sqrt_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_svml_sqrt_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_tan_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_tan_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_tand_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_tand_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_tanh_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_tanh_ps(ddi_4 _a);
ddi_2 _igen_dd_fb_mm_trunc_pd(ddi_2 _a);
ddi_4 _igen_dd_fb_mm_trunc_ps(ddi_4 _a);
ddi_4 _igen_dd_fb_mm256_acos_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_acos_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_acosh_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_acosh_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_asin_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_asin_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_asinh_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_asinh_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_atan_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_atan_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_atan2_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_atan2_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_atanh_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_atanh_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_cbrt_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_cbrt_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_cdfnorm_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_cdfnorm_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_cdfnorminv_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_cdfnorminv_ps(ddi_8 _a);
ddi_8 _igen_dd_fb_mm256_cexp_ps(ddi_8 _a);
ddi_8 _igen_dd_fb_mm256_clog_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_cos_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_cos_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_cosd_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_cosd_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_cosh_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_cosh_ps(ddi_8 _a);
ddi_8 _igen_dd_fb_mm256_csqrt_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_erf_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_erf_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_erfc_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_erfc_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_erfcinv_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_erfcinv_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_erfinv_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_erfinv_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_exp_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_exp_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_exp10_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_exp10_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_exp2_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_exp2_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_expm1_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_expm1_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_hypot_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_hypot_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_invcbrt_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_invcbrt_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_invsqrt_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_invsqrt_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_log_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_log_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_log10_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_log10_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_log1p_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_log1p_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_log2_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_log2_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_logb_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_logb_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_pow_pd(ddi_4 _a, ddi_4 _b);
ddi_8 _igen_dd_fb_mm256_pow_ps(ddi_8 _a, ddi_8 _b);
ddi_4 _igen_dd_fb_mm256_sin_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_sin_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_sincos_pd(ddi_4 *_mem_addr, ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_sincos_ps(ddi_8 *_mem_addr, ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_sind_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_sind_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_sinh_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_sinh_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_svml_ceil_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_svml_ceil_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_svml_floor_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_svml_floor_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_svml_round_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_svml_round_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_svml_sqrt_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_svml_sqrt_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_tan_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_tan_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_tand_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_tand_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_tanh_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_tanh_ps(ddi_8 _a);
ddi_4 _igen_dd_fb_mm256_trunc_pd(ddi_4 _a);
ddi_8 _igen_dd_fb_mm256_trunc_ps(ddi_8 _a);
ddi_8 _igen_dd_fb_mm256_cvtph_ps(__m128i _a);
__m128i _igen_dd_fb_mm256_cvtps_ph(ddi_8 _a, int rounding);
dd_I _igen_dd_fb_mm256_cvtss_f32(ddi_8 _a);
dd_I _igen_dd_fb_mm256_cvtsd_f64(ddi_4 _a);
ddi_8 _igen_dd_fb_mm512_acos_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_acos_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_acos_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_acos_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_acosh_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_acosh_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_acosh_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_acosh_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_asin_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_asin_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_asin_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_asin_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_asinh_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_asinh_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_asinh_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_asinh_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_atan2_pd(ddi_8 _a, ddi_8 _b);
ddi_8 _igen_dd_fb_mm512_mask_atan2_pd(ddi_8 _src, __mmask8 k, ddi_8 _a,
                                    ddi_8 _b);
ddi_16 _igen_dd_fb_mm512_atan2_ps(ddi_16 _a, ddi_16 _b);
ddi_16 _igen_dd_fb_mm512_mask_atan2_ps(ddi_16 _src, __mmask16 k, ddi_16 _a,
                                     ddi_16 _b);
ddi_8 _igen_dd_fb_mm512_atan_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_atan_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_atan_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_atan_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_atanh_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_atanh_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_atanh_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_atanh_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_cbrt_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_cbrt_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_cbrt_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_cbrt_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_cdfnorm_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_cdfnorm_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_cdfnorm_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_cdfnorm_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_cdfnorminv_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_cdfnorminv_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_cdfnorminv_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_cdfnorminv_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_ceil_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_ceil_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_ceil_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_ceil_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_cos_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_cos_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_cos_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_cos_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_cosd_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_cosd_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_cosd_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_cosd_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_cosh_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_cosh_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_cosh_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_cosh_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_erf_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_erf_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_erfc_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_erfc_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_erf_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_erf_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_erfc_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_erfc_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_erfinv_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_erfinv_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_erfinv_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_erfinv_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_erfcinv_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_erfcinv_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_erfcinv_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_erfcinv_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_exp10_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_exp10_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_exp10_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_exp10_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_exp2_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_exp2_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_exp2_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_exp2_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_exp_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_exp_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_exp_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_exp_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_expm1_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_expm1_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_expm1_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_expm1_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_floor_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_floor_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_floor_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_floor_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_hypot_pd(ddi_8 _a, ddi_8 _b);
ddi_8 _igen_dd_fb_mm512_mask_hypot_pd(ddi_8 _src, __mmask8 k, ddi_8 _a,
                                    ddi_8 _b);
ddi_16 _igen_dd_fb_mm512_hypot_ps(ddi_16 _a, ddi_16 _b);
ddi_16 _igen_dd_fb_mm512_mask_hypot_ps(ddi_16 _src, __mmask16 k, ddi_16 _a,
                                     ddi_16 _b);
ddi_8 _igen_dd_fb_mm512_invsqrt_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_invsqrt_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_invsqrt_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_invsqrt_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_log10_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_log10_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_log10_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_log10_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_log1p_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_log1p_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_log1p_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_log1p_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_log2_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_log2_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_log_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_log_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_log_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_log_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_logb_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_logb_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_logb_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_logb_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_nearbyint_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_nearbyint_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_nearbyint_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_nearbyint_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_pow_pd(ddi_8 _a, ddi_8 _b);
ddi_8 _igen_dd_fb_mm512_mask_pow_pd(ddi_8 _src, __mmask8 k, ddi_8 _a,
                                  ddi_8 _b);
ddi_16 _igen_dd_fb_mm512_pow_ps(ddi_16 _a, ddi_16 _b);
ddi_16 _igen_dd_fb_mm512_mask_pow_ps(ddi_16 _src, __mmask16 k, ddi_16 _a,
                                   ddi_16 _b);
ddi_8 _igen_dd_fb_mm512_recip_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_recip_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_recip_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_recip_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_rint_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_rint_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_rint_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_rint_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_svml_round_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_svml_round_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_sin_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_sin_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_sin_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_sin_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_sinh_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_sinh_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_sinh_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_sinh_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_sind_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_sind_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_sind_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_sind_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_tan_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_tan_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_tan_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_tan_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_tand_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_tand_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_tand_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_tand_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_tanh_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_tanh_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_tanh_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_tanh_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_trunc_pd(ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_trunc_pd(ddi_8 _src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_trunc_ps(ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_trunc_ps(ddi_16 _src, __mmask16 k, ddi_16 _a);
ddi_8 _igen_dd_fb_mm512_sincos_pd(ddi_8 *_cos_res, ddi_8 _a);
ddi_8 _igen_dd_fb_mm512_mask_sincos_pd(ddi_8 *_cos_res, ddi_8 _sin_src,
                                     ddi_8 _cos_src, __mmask8 k, ddi_8 _a);
ddi_16 _igen_dd_fb_mm512_sincos_ps(ddi_16 *_cos_res, ddi_16 _a);
ddi_16 _igen_dd_fb_mm512_mask_sincos_ps(ddi_16 *_cos_res, ddi_16 _sin_src,
                                      ddi_16 _cos_src, __mmask16 k, ddi_16 _a);
#ifdef __cplusplus
}
#endif
